package testpackage.content.repetition.stringlists;

/**
 * User: mtitov
 * Date: 2/7/12
 * Time: 1:01 PM
 */
public class StringListArchive {

    public static String[] listened = {
            "Baha Men" +
                    "WHO LET THE DOGS OUT" +
                    "Decade-End Independent Albums",
            "JOHN MAYER" +
                    "1999 - Inside Wants Out (EP) (00:31:51) 320kbps\n" +
                    "2001 - Room for Squares (00:54:10) 320kbps\n" +
                    "2003 - Heavier Things (00:46:14) 320kbps\n" +
                    "2006 - Continuum (00:49:54) 320kbps\n" +
                    "2009 - Battle Studies (00:46:39) 320kbps" +
                    "Year-End Rock Album Artists",
            "NORAH JONES" +
                    "2001 First Sessions (EP), " +
                    "2002 Come Away With Me (Japan Limited Edition)\n" +
                    "2003 Turn Me On (CD Single)\n" +
                    "2004 Feels Like Home (Deluxe Edition)\n" +
                    "2007 Not Too Late\n" +
                    "2007 The Story (Promo CD)\n" +
                    "2009 The Fall (Deluxe Edition)\n" +
                    "2010 Chasing Pirates (Remix EP)\n" +
                    "2010 ...Featuring" +
                    "Decade-End Jazz Artists",
            "Susan Boyle" +
                    "I DREAMED A DREAM" +
                    "Year-End Top Billboard 200"};

    public static String[] music = {"Hot 100",
            "Billboard 200",
            "Radio Songs",
            "Hot Digital Songs",
            "Digital Albums",
            "Social 50",
            "Uncharted",
            "Ringtones",
            "Heatseekers Songs",
            "Heatseekers Albums",
            "Pop Songs",
            "Adult Contemporary",
            "Adult Pop Songs",
            "Dance/Club Play Songs",
            "Dance/Electronic Albums",
            "R&B/Hip-Hop Songs",
            "Top R&B/Hip-Hop Albums",
            "Rap Songs",
            "Rap Albums",
            "Rock Songs",
            "Rock Albums",
            "Alternative Songs",
            "Alternative Albums",
            "Hard Rock Albums",
            "Folk Albums",
            "Country Songs",
            "Country Albums",
            "Bluegrass Albums",
            "Jazz Songs",
            "Jazz Albums",
            "Blues Albums",
            "Classical Albums",
            "Latin Songs",
            "Latin Albums",
            "Regional Mexican Songs",
            "Regional Mexican Albums",
            "Latin Pop Songs",
            "Latin Pop Albums",
            "Tropical Songs",
            "Tropical Albums",
            "Christian Songs",
            "Christian Albums",
            "Gospel Songs",
            "Gospel Albums",
            "Independent Albums",
            "Top Catalog Albums",
            "Holiday Albums",
            "Holiday Songs",
            "Reggae Albums",
            "World Albums",
            "New Age Albums",
            "Comedy Albums",
            "Kids Albums",
            "Soundtracks",
            "Tastemaker Albums",
            "Japan Hot 100",
            "Korea K-Pop Hot 100",
            "The Official U.K. Singles Chart",
            "The Official U.K. Albums Chart",
            "Germany Songs",
            "German Albums",
            "Billboard Canadian Hot 100",
            "Canadian Albums",
            "YouTube",
            "AOL Radio",
            "Yahoo Video",
            "Yahoo Audio",
            "MySpace Songs",
            "Next Big Sound 25",
            "Eventful: Most Demanded Performers",
            "Eventful: Today's Hottest Demands",
            "Year-End Top Artists",
            "Year-End Top New Artists",
            "Year-End Hot 100 Songs",
            "Year-End Hot 100 Artists",
            "Year-End Top Billboard 200",
            "Year-End Top Billboard 200 Artists",
            "Year-End Hot Radio Songs",
            "Year-End Hot Digital Songs",
            "Year-End Hot Digital Songs Artists",
            "Year-End Ringtones",
            "Year-End Ringtones Artists",
            "Year-End Digital Albums",
            "Year-End Digital Album Artists",
            "Year-End Pop Songs",
            "Year-End Pop Songs Artists",
            "Year-End Adult Contemporary Songs",
            "Year-End Adult Contemporary Artists",
            "Year-End Adult Pop Songs",
            "Year-End Adult Pop Songs Artists",
            "Year-End Dance Club Songs",
            "Year-End Dance Club Artists",
            "Year-End Dance/Electronic Albums",
            "Year-End Dance/Electronic Album Artists",
            "Year-End Hot R&B/Hip-Hop Songs",
            "Year-End Hot R&B/Hip-Hop Songs Artists",
            "Year-End Top R&B/Hip-Hop Albums",
            "Year-End Top R&B/Hip-Hop Album Artists",
            "Year-End Rap Songs",
            "Year-End Rap Songs Artists",
            "Year-End Rap Albums",
            "Year-End Rap Album Artists",
            "Year-End Rock Songs",
            "Year-End Rock Songs Artists",
            "Year-End Rock Albums",
            "Year-End Rock Album Artists",
            "Year-End Alternative Songs",
            "Year-End Alternative Songs Artists",
            "Year-End Alternative Albums",
            "Year-End Alternative Album Artists",
            "Year-End Hard Rock Albums",
            "Year-End Hard Rock Album Artists",
            "Year-End Folk Albums",
            "Year-End Folk Artists",
            "Year-End Hot Country Songs",
            "Year-End Hot Country Songs Artists",
            "Year-End Top Country Albums",
            "Year-End Top Country Album Artists",
            "Year-End Bluegrass Albums",
            "Year-End Bluegrass Artists",
            "Year-End Smooth Jazz Songs",
            "Year-End Smooth Jazz Songs Artists",
            "Year-End Jazz Albums",
            "Year-End Jazz Album Artists",
            "Year-End Blues Albums",
            "Year-End Blues Artists",
            "Year-End Classical Albums",
            "Year-End Classical Artists",
            "Year-End Hot Latin Songs",
            "Year-End Hot Latin Songs Artists",
            "Year-End Top Latin Albums",
            "Year-End Top Latin Album Artists",
            "Year-End Regional Mexican Songs",
            "Year-End Regional Mexican Songs Artists",
            "Year-End Regional Mexican Albums",
            "Year-End Regional Mexican Album Artists",
            "Year-End Latin Pop Songs",
            "Year-End Latin Pop Songs Artists",
            "Year-End Latin Pop Albums",
            "Year-End Latin Pop Album Artists",
            "Year-End Tropical Songs",
            "Year-End Tropical Songs Artists",
            "Year-End Tropical Albums",
            "Year-End Tropical Album Artists",
            "Year-End Christian Songs",
            "Year-End Christian Songs Artists",
            "Year-End Christian Albums",
            "Year-End Christian Album Artists",
            "Year-End Gospel Songs",
            "Year-End Gospel Songs Artists",
            "Year-End Gospel Albums",
            "Year-End Gospel Album Artists",
            "Year-End Independent Albums",
            "Year-End Independent Artists",
            "Year-End Pop Catalog Albums",
            "Year-End Pop Catalog Artists",
            "Year-End Reggae Albums",
            "Year-End Reggae Artists",
            "Year-End World Albums",
            "Year-End World Album Artists",
            "Year-End New Age Albums",
            "Year-End New Age Artists",
            "Year-End Comedy Albums",
            "Year-End Comedy Artists",
            "Year-End Kid Audio",
            "Year-End Kid Artists",
            "Year-End Soundtracks Albums",
            "Year-End European Hot 100 Singles",
            "Year-End European Top 100 Albums",
            "Year-End Japan Hot 100",
            "Year-End Canadian Hot 100",
            "Year-End Canadian Hot 100 Artists",
            "Year-End Top Canadian Albums",
            "Decade-End Artists Of The Decade",
            "Decade-End Hot 100 Artists",
            "Decade-End Hot 100 Songs",
            "Decade-End Billboard 200 Artists",
            "Decade-End Billboard 200 Albums",
            "Decade-End Radio Songs",
            "Decade-End Radio Songs Artists",
            "Decade-End Digital Songs Artists",
            "Decade-End Digital Songs",
            "Decade-End Ringtones",
            "Decade-End Ringtones Artists",
            "Decade-End Digital Albums",
            "Decade-End Digital Album Artists",
            "Decade-End Pop Songs Artists",
            "Decade-End Pop Songs",
            "Decade-End Adult Contemporary Artists",
            "Decade-End Adult Contemporary",
            "Decade-End Adult Pop Songs",
            "Decade-End Adult Pop Artists",
            "Decade-End Dance/Club Play Songs",
            "Decade-End Dance/Club Play Artists",
            "Decade-End Dance/Electronic Albums",
            "Decade-End Dance/Electronic Artists",
            "Decade-End R&B/Hip-Hop Songs",
            "Decade-End R&B/Hip-Hop Albums",
            "Decade-End R&B/Hip-Hop Artists",
            "Decade-End Rap Songs Artists",
            "Decade-End Rap Songs",
            "Decade-End Rock Songs",
            "Decade-End Rock Songs Artists",
            "Decade-End Alternative Artists",
            "Decade-End Alternative Songs",
            "Decade-End Country Songs",
            "Decade-End Country Albums",
            "Decade-End Country Artists",
            "Decade-End Jazz Albums",
            "Decade-End Jazz Artists",
            "Decade-End Blues Albums",
            "Decade-End Blues Artists",
            "Decade-End Classical Albums",
            "Decade-End Classical Artists",
            "Decade-End Latin Songs",
            "Decade-End Latin Artists",
            "Decade-End Latin Albums",
            "Decade-End Regional Mexican Songs",
            "Decade-End Regional Mexican Songs Artists",
            "Decade-End Regional Mexican Albums",
            "Decade-End Regional Mexican Album Artists",
            "Decade-End Latin Pop Songs",
            "Decade-End Latin Pop Songs Artists",
            "Decade-End Latin Pop Albums",
            "Decade-End Latin Pop Album Artists",
            "Decade-End Tropical Song Artists",
            "Decade-End Tropical Songs",
            "Decade-End Tropical Album Artists",
            "Decade-End Tropical Albums",
            "Decade-End Christian Songs Artists",
            "Decade-End Christian Songs",
            "Decade-End Christian Album Artists",
            "Decade-End Christian Albums",
            "Decade-End Gospel Album Artists",
            "Decade-End Gospel Albums",
            "Decade-End Independent Album Artists",
            "Decade-End Independent Albums",
            "Decade-End Catalog Albums",
            "Decade-End Catalog Album Artists",
            "Decade-End Holiday Albums",
            "Decade-End Reggae Albums",
            "Decade-End Reggae Artists",
            "Decade-End World Albums",
            "Decade-End World Artists",
            "Decade-End New Age Artists",
            "Decade-End New Age Albums",
            "Decade-End Comedy Albums",
            "Decade-End Comedy Artists",
            "Decade-End Kids Albums",
            "Decade-End Kid Artists",
            "Decade-End Soundtracks"};

    public static String[] food = {"овощи",
            "фрукты",
            "мясо",
            "рыба",
            "орехи",
            "молочные продукты",
            "бобовые",
            "хлеб",
            "макароны из твердых сортов пшеницы",
            "ягоды",
            "зелень",
            "птица",
            "яйца"
    };

}
