package testpackage.content.repetition.stringlists;

import java.util.EnumSet;

/**
 * User: mtitov
 * Date: 11/2/11
 * Time: 10:05 AM
 */
public enum StringType implements StringTypeInterface {

    A_SALADS(getSalads()), B_SOUPS(getSoups()), BOOKS(getBooks()), C_SECOND_COURSES(getSecondCourses()), CHILDREN_FOOD(getChildrenFood()), D_MEAT(getMeat()),
    FOOD(getFood()), FOOTBALL_PARTNERS(getFootballPartners()), GAMES(getGames()), KNOWLEDGE_AREAS(getKnowledgeAreas()),
    MACDONALDS(getMacdonalds()), MUSIC(getMusic()), PASSIVE_BALANCE_PROGRAM(getPassiveBalanceProgram()),
    PUZZLES(getPuzzles()), TENNIS_PARTNERS(getTennisPartners()), TOYS(getToys()), WALLPAPERS(getWallpapers()),
    ZAYTSEV_GAMES(getZaytsevGames());

    public static final EnumSet<StringType> DISH_TYPES = EnumSet.of(A_SALADS, B_SOUPS, C_SECOND_COURSES, D_MEAT);

    StringType(String[] list) {
        this.list = list;
    }

    public String[] getList() {
        return list;
    }

    private String[] list;

    public static String[] getBooks() {
        return StringListHolder.books;
    }

    public static String[] getGames() {
        return StringListHolder.games;
    }

    public static String[] getChildrenFood() {
        return StringListHolder.childrenFood;
    }

    public static String[] getZaytsevGames() {
        return StringListHolder.zaytsev;
    }

    public static String[] getPassiveBalanceProgram() {
        return StringListHolder.passiveBalanceProgram;
    }

    public static String[] getFood() {
        return StringListArchive.food;
    }

    public static String[] getKnowledgeAreas() {
        return StringListHolder.knowledgeAreas;
    }

    public static String[] getMusic() {
        return StringListArchive.music;
    }

    public static String[] getPuzzles() {
        return StringListHolder.puzzles;
    }

    public static String[] getMeat() {
        return StringListHolder.allMeat;
    }

    public static String[] getSalads() {
        return StringListHolder.allSalads;
    }

    public static String[] getSecondCourses() {
        return StringListHolder.allSecondCourses;
    }

    public static String[] getSoups() {
        return StringListHolder.allSoups;
    }

    public static String[] getTennisPartners() {
        return StringListHolder.tennisPartners;
    }

    public static String[] getFootballPartners() {
        return StringListHolder.footballPartners;
    }

    public static String[] getWallpapers() {
        return StringListHolder.wallpapers;
    }

    public static String[] getMacdonalds() {
        return StringListHolder.macdonalds;
    }

    public static String[] getToys() {
        return StringListHolder.toys;
    }

    private static class StringListHolder {

        public static String[] books = {
                "Лошадка",
                "Зима",
                "Белочка",
                "В деревне",
                "Овощи",
                "Слоненок",
                "Гав",
                "Фрукты",
                "Маша-растеряша",
                "Мамы и малыши",
                "Мои игрушки",
                "Барто",
                "На отдыхе",
                "Перед сном",
                "Азбука",
                "Удивительные звери",
                "Гуси-лебеди",
                "Домашние животные",
                "Транспорт",
                "Зоопарк",
                "Малыши"
        };

        public static String[] childrenFood = {
//                молочных продуктов (детские творог, сыр, сметану и сливки)
//                постная говядина, свинина, телятина, курица, индейка, кролик, нежирная рыба (судак, хек, треска)
//                печень и язык
//                мясное в баночках
//                рыба, рыбное в баночках
//                любые овощи, включая свеклы, редиса, репы и остальные, укроп и петрушку, листовой салат и зеленый лук
//                готовые овощные пюре в баночках
//                ржаной Хлеб и каша
//                печенье, а также кукурузные хлопья, мюсли и макаронные изделия
//                омлет из цельного яйца
//                грушам, яблокам, бананам и сливам, апельсины, абрикосы, персики, киви, клубника, лимоны,
//                вишня, смородина, крыжовник, клюква, ежевика, малина и брусника
//                детских фруктовых пюре, компоты из свежих фруктов и соки (свежевыжатые или с маркировкой "для детского питания")
//                детским фруктовым и травяным чаям
        };

        public static String[] toys = {
                "африка",
                "ведро",
                "грабли",
                "грузовик",
                "джип",
                "жук",
                "змейка",
                "змейка с зеркалом",
                "зубы брелок",
                "каталка",
                "колечко резиновое ",
                "коляска",
                "конструктор",
                "кубики 4",
                "кубики Зайцева",
                "кубики мягкие",
                "кубики пластиковые",
                "кукла говорящая",
                "кукла девочка",
                "кукла девочка большая",
                "кукла маленькая желтая",
                "кукла маленькая синяя",
                "лодка желтая",
                "лодка красная",
                "лодка синяя",
                "лопата железная",
                "лопата красная квадратная",
                "лопата красная круглая",
                "лошадь",
                "лошадь белая",
                "машина красная",
                "машина пожарная",
                "машинка с большими колесами",
                "машина синяя",
                "машинка желтая",
                "машинка синяя",
                "машинка синяя с лопатой",
                "миша",
                "миша большой",
                "миша брелок",
                "молоток",
                "мяч арбуз",
                "мяч желтый большой",
                "мяч желтый маленький",
                "мяч желтый средний",
                "мяч зеленый",
                "мяч красный большой",
                "мяч розовый",
                "мяч светящийся",
                "мяч синий маленький",
                "мяч синий средний",
                "мячик арбуз",
                "мячик желтый",
                "мячик футбольный",
                "надевалка деревянная",
                "надевалка пластик",
                "обезьяна",
                "паска ананас",
                "паска бананы",
                "паска виноград",
                "паска вишня",
                "паска клубника",
                "паска краб",
                "пирамида",
                "пищалка ананас",
                "пищалка мишка",
                "пищалка утенок",
                "пищалка утка",
                "погремушка зубы желтая",
                "погремушка зубы синяя",
                "погремушка желто-зеленая",
                "погремушка клоуны",
                "погремушка мишки",
                "погремушка оранжевая",
                "погремушка с шариком",
                "треножка",
                "погремушка шарик",
                "свинья",
                "театр баба",
                "театр дед",
                "театр козлик",
                "театр корова",
                "театр медведь",
                "тигр",
                "тракторы",
                "рыбка",
                "фигуры",
                "червяк",
                "шнуровка",
                "юла"
        };

        public static String[] salads = {
                "винегрет",
                "капуста квашеная",
                "морковь и селера",
                "свекла",
                "спаржевый",
                "огурцы и помидоры",
                "редис с капустой"
        };

        public static String[] allSalads = {
                "Жюльен с грибами и курицей",
                "Закуска острая",
                "Огурец соленый",
                "Сельдь с луком",
                "Селедка под шубой",
                "Помидор соленый",
                "Сало с чесноком",
                "Торт из кабачков",
                "Салат Винегрет",
                "Салат из грибов",
                "Салат из квашеной капусты",
                "Салат с крабовыми палочками",
                "Салат с курицей и ананасом",
                "Салат с курицей и грибами",
                "Салат из моркови и сельдерея",
                "Салат из краснокочанной капусты",
                "Салат с ветчиной",
                "Салат Лососевый",
                "Салат Морковь по-корейски",
                "Салат Мимоза",
                "Салат Оливье",
                "Салат Спаржевый",
                "Салат Цезарь с курицей",
                "Салат-фреш Греческий",
                "Салат-фреш с курицей",
                "Салат-фреш с тунцом"
        };

        public static String[] allSoups = {
                "Борщ украинский",
                "Бульон куриный с лапшой",
                "Рассольник",
                "Солянка мясная",
                "Суп гороховый",
                "Суп овощной",
                "Юшка грибная с фасолью",
                "Уха из рыбы"
        };

        public static String[] allMeat = {
                "Биточки по-селянски",
                "Бигус",
                "Бризол фирменный",
                "Отбивная из свинины",
                "Голубцы с мясом",
                "Колбаса домашняя",
                "Колбаски охотничьи (порц.)",
                "Котлета домашняя",
                "Котлета мясная с сулугуни",
                "Котлета полтавская",
                "Котлета Садко",
                "Жаркое по-домашнему",
                "Печень жареная",
                "Ребра жареные",
                "Сосиски вареные",
                "Стейк из телятины",
                "Стейк из свинины",
                "Телятина отварная",
                "Тефтели мясные",
                "Шашлык из свинины",
                "Говядина в сыре",
                "Бризоль рыбный",
                "Котлета рыбная Бужок",
                "Котлета рыбная с маслом",
                "Котлета рыбная паровая",
                "Котлета рыбная жареная",
                "Крученик рыбный",
                "Лосось запеченный",
                "Рыба с овощами",
                "Рыба под маринадом",
                "Рыба по-итальянски",
                "Рыба жареная",
                "Стейки из лосося",
                "Скумбрия припущенная",
                "Колбаса куриная",
                "Котлета куриная с овощами и грибами",
                "Котлета куриная с сыром",
                "Котлета куриная паровая",
                "Котлета куриная по-домашнему",
                "Котлета по-киевски",
                "Крученик куриный с омлетом",
                "Курица запеченная с картофелем",
                "Куриная отбивная под сыром",
                "Куриные крылышки в маринаде",
                "Куриные крылышки жареные",
                "Куриные потрошки в сливочном соусе",
                "Куриные окорочка жареные",
                "Печень куриная жареная",
                "Стейк куриный",
                "Тефтели куриные",
                "Шашлык куриный"
        };

        public static String[] allSecondCourses = {
                "Баклажаны с курицей",
                "Гречка",
                "Грибы жареные",
                "Гуляш с мясом",
                "Капуста тушеная",
                "Картофель вареный",
                "Картофель по-полтавски",
                "Картофель жареный",
                "Фасоль с овощами и грибами",
                "Макароны в соусе",
                "Овощи бланшированные",
                "Овощи с беконом",
                "Перец фаршированный мясом",
                "Шампиньоны в сметане",
                "Плов",
                "Рагу овощное",
                "Рис",
                "Рис с морепродуктами",
                "Рис с овощами",
                "Соте",
                "Сырники",
                "Вареники с вишнями",
                "Вареники с капустой",
                "Вареники с картошкой",
                "Вареники с мясом",
                "Зразы картофельные с капустой и грибами",
                "Блины с маком",
                "Блинчики с мясом",
                "Блины с творогом",
                "Блины с яблоками",
                "Блинчики с мясом в яйце",
                "Пирожок с капустой",
                "Пирожок с мясом (печенью)",
                "Пирожок с вишнями",
                "Пирожок жареный с капустой",
                "Пирожок жареный с картофелем",
                "Пирожок жареный с мясом",
                "Пирожок жареный с печенью и картофелем"
        };

        public static String[] soups = {
                "Овощной",
                "Гороховый",
                "Рыбная юшка",
                "грибная юшка",
                "окрошка",
                "капустняк",
                "борщ зелёный",
                "борщ"
        };

        public static String[] secondCourses = {
                "Овощи бланшированные",
                "Гречка",
                "Капуста тушеная",
                "рагу овощное",
                "фасоль с овощами",
                "сырная запеканка"
        };

        public static String[] meat = {
                "котлета по-киевски",
                "котлета садко",
                "куриная колбаска",
                "куриная котлета в беконе",
                "куриная котлета паровая",
                "куриная котлета по-домашнему",
                "куриная котлета c овощами и грибами",
                "куриная ножка",
                "куриная отбивная",
                "куриный стейк",
                "куриный шашлык",
                "лосось жареный",
                "лосось запеченный",
                "лосось запеченный с зелёным маслом",
                "рыба, запеченная с овощами",
                "рыба, запеченная с грибами в сыре",
                "рыба в кунжуте",
                "рыба жареная",
                "рыба по-итальянски",
                "рыбная котлета бужок",
                "рыбная паровая котлета",
                "рыбный крученик",
                "рыбный сеченик",
                "рыбный шашлык",
                "cельдь с луком",
                "печень",
                "бризоль"
        };

        public static String[] tennisPartners = {
                "Starykov Anton",
                "Taras Re skype",
                "Artem Drobushko skype",
                "Sasha Gamanjuk skype",
                "Dima Bol skype",
                "Andrii Bubnov skype",
                "Vadym Mischenko skype",
                "Volodymyr Iurtaiev",
                "Roman Bielkin",
                "Oleksandr Karetnyi",
                "Sergii Liushkov",
                "Kolya lysyy from 703",
                "Boris Bovdui skype"
        };

        public static String[] footballPartners = {
                "Sabina Krupko"
        };

        public static String[] games = {
                "Разноцветные огоньки",
                "Пять пальцев",
                "Сорока-Белобока",
                "ЗамОк",
                "Ягодки",
                "Рыбки",
                "Этот сливку поднимает",
                "У тебя есть рублик",
                "башенки из пустых коробочек",
                "Пальчиковые краски",
                "Мячи",
                "Колокольчик",
                "Пирамида",
                "Кукла нельзя",
                "Поделиться",
                "Помощь",
                "дай возьми",
                "Книжки",
                "да",
                "Лепка из теста (позже из пластилина)",
                "игра посудой",
                "переливание воды",
                "пересыпание круп",
                "Хлоп - шлёп 1",
                "Хлоп - шлёп 2",
                "Хлоп - шлёп 3",
                "нарисованный лабиринт",
                "обведение предметов и штрихование фигурок",
                "шнуровки",
                "составление бус (настоящих)",
                "перерисовывание примера дорожки",
                "аппликации",
                "плетение ковриков из полосок бумаги",
                "кубики 6-8 штук",
                "конструктор",
                "грузовик",
                "Ку-ку",
                "Рисование мелками",
                "Раскрашивание",
                "оригами",
                "кораблики из губок",
                "прыгаем - на воздухе",
                "лупа - на воздухе",
                "рамки-вкладыши (кубик с прорезями)",
                "Игры из мягкого материала в ванну",
                "Логический поезд",//1.5 - 3 года
                "Детское лото распознавания",//1.5 - 3 года
                "Детское лото заполнение",//1.5 - 3 года
                "Детское лото дополнение",//1.5 - 3 года
                "Волшебная липучка",//1.5 - 3 года
                "Это папа",
                "Игра для различия цвета",
                "Что лишнее?",
                "Hайди паpу",
                "Что плавает?",
                "Входит и выходит",
                "Ролевые игры",
                "Ролевые игры общение с животным",
                "Ролевые игры кормить куклу",
                "раздевать куклу",
                "Ролевые игры ехать в машине в стульчике",
                "кукольный театр родители показывают",
                "кукольный театр малыши показывают",
                "игры с нарисованными зверями",
                "маленькие игрушки в домиках",
                "катание зверей на лыжах",
                "магазин",
                "обыграть ситуацию, поменяться местами",
                "Вкладыши в основание",
                "Вкладыши один в другой (матрешка и т.п.)",
                "крупная мозаика с деталями геометрической формы",//1,5 - 2
                "Блоки и конструкторы сюжетные (с фигурками)",
                "Квадраты Никитина",
                "Дроби никитина",
                "Сложи узор Никитина",
                "Радужное лукошко Даниловой",
                "Складушки Красноухова",
                "Детское домино с цветными картинками (сопоставлять по признакам)",
                "блоки Дьенеша (сопоставлять по признакам)",
                "Тренажеры речевые",
                "Разрезные картинки",
                "Кто что ест",
                "Веселая пантомима",
                "спектакль с книгами-декорациями",
                "сравнение изображений с одинаковым смыслом",
                "пруд из кубиков",
                "бусы из макарон",
                "сортировать макароны",
                "Диафильмы",
                "Рыбалка",
                "Где же лужа?",
                "Поймай-ка!",
                "как льется или капает вода из крана",
                "как по-разному звенит чайная ложка в пустом стакане или чашке с водой",
                "как громко пересыпается в стеклянный стакан горошек и тихо - манка",
                "Вот идет мышка - на воздухе",
                "Прокати мяч через тоннель - на воздухе",
                "Бегом к дереву - на воздухе",
                "Лови мяч - на воздухе",
                "Одеяло с сюрпризом - на воздухе",
                "Игра в песочек - на воздухе",
                "какое дерево выше, какое ниже; у какого дерева листик шире, а у какого уже",
                "Домики, норки и берлоги",
                "прятки зверей",
                "Рыба, птица, зверь",
        };

        public static String[] zaytsev = {
                "Дорожки",
                "Маленькие дорожки",
                "поиграть несколько кубиков",
                "Домики",
                "Перекладывание",
                "Писать окружающее",
                "дежурный кубик",
                "новая Игрушки на кубиках",
                "Активная игра в кубики",
                "Активный словарь",
                "Чтение про себя",
                "Перевертыши",
                "Игрушки пишут слова",
                "Пишем кубиками"
        };

        public static String[] passiveBalanceProgram = {
                "Горизонтальное верчение ничком",
                "Горизонтальное верчение Левый бок",
                "Горизонтальное верчение Правый бок",
                "Покачивание вдвоём как в колыбели",
                "Горизонтальное вращение на животе",
                "Горизонтальное вращение на спине",
                "Горизонтальное вращение за 2 руки",
                "Покачивание вдвоём как на качелях",
                "Ускорение",
                "вниз головой (ложить на спину)"
        };

        public static String[] solvedPuzzles = {"Вино и вода",
                "Вот так телефонистки!",
                "Красный нос в землю врос, ",
                "Пошутил над мудрецами",
                "Триэль",
                "Чай",
                "Я - сборник карт. От ударенья"
        };

        public static String[] puzzles = {"Забавные головоломки",
                "Задачи с подвохом",
                "Старинные и сказочные головоломки",
                "Алгоритмы",
                "Вероятности Триэль",
                "Вычисления Вино и вода",
                "Геометрия",
                "Комбинаторика",
                "Логика и рассуждения",
                "Принцип Дирихле",
                "Соответствия",
                "Числовые ребусы",
                "Задачи из книги Р. Смаллиана 'Как же называется эта книга?'",
                "Загадки про время",
                "Задачи со словами",
                "Анаграммы",
                "Антифразы",
                "Логогрифы",
                "Метаграммы",
                "Омографы",
                "Омонимы",
                "Псевдонаучный бред",
                "Шарады",
                "Несерьезные головоломки",
                "Физические задачи",
                "Загадки про природные явления",
                "Загадки про животных",
                "Загадки про растения",
                "Загадки про инструменты и предметы",
                "Прочие загадки",
                "Задачи на взвешивание и переливание",
                "Головоломки со спичками",
                "Последовательности и ряды",
                "Задачи для нестандартно мыслящих",
                "Логические трюки и парадоксы",
                "Исторические задачи",
                "Фокусы",
                "Задачи из сборника головоломок общества МЕНСА",
                "WWW-задачи"};

        private static String[] usedWallpapers = {
                "Авиация" + "http://desktopwallpapers.org.ua/aviation/3659-samolet-v-nebe-sineva-oblaka-nad-golovoj-proletaya.html",
                "Авиация" + "http://desktopwallpapers.org.ua/aviation/3660-nepogoda-zapreshheno-vzletat-samolet-prolivnoj-dozhd-otrazhenie-posadochnyj-ogni.html",
                "Минимализм" + "http://desktopwallpapers.org.ua/minimalize/3039-dym-krasnye-klubni-krasnoe-vino.html",
                "текстуры" + "http://desktopwallpapers.org.ua/textures/2690-bruschatka-kamushki-doroga-kubiki.html"
        };

        private static String[] macdonalds = {
                "Дабл Чiзбургер"
        };

        public static String[] wallpapers = {"Еда",
                "Животные",
                "Животные",
                "Гав-гав-ры-рыы",
                "Гав-гав-ры-рыы",
                "Гав-гав-ры-рыы",
                "Мотоциклы",
                "Мотоциклы",
                "Мотоциклы",
                "Мотоциклы",
                "оружие",
                "оружие",
                "оружие",
                "оружие",
                "оружие",
                "Автомобили",
                "Автомобили",
                "Автомобили",
                "Автомобили",
                "Автомобили",
                "Автомобили",
                "Авиация",
                "Авиация",
                "Авиация",
                "Авиация",
                "Авиация",
                "Авиация",
                "Авиация",
                "весна",
                "весна",
                "весна",
                "весна",
                "весна",
                "весна",
                "весна",
                "весна",
                "лето",
                "лето",
                "лето",
                "лето",
                "лето",
                "лето",
                "лето",
                "лето",
                "лето",
                "зима",
                "зима",
                "зима",
                "зима",
                "зима",
                "зима",
                "зима",
                "зима",
                "зима",
                "зима",
                "Фэнтези",
                "Фэнтези",
                "Фэнтези",
                "Фэнтези",
                "Фэнтези",
                "Фэнтези",
                "Фэнтези",
                "Фэнтези",
                "Фэнтези",
                "Фэнтези",
                "Фэнтези",
                "Города",
                "Города",
                "Города",
                "Города",
                "Города",
                "Города",
                "Города",
                "Города",
                "Города",
                "Города",
                "Города",
                "Города",
                "осень",
                "осень",
                "осень",
                "осень",
                "осень",
                "осень",
                "осень",
                "осень",
                "осень",
                "осень",
                "осень",
                "осень",
                "осень",
                "природа",
                "природа",
                "природа",
                "природа",
                "природа",
                "природа",
                "природа",
                "природа",
                "природа",
                "природа",
                "природа",
                "природа",
                "природа",
                "природа",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "3d",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Макро",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "Минимализм",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "космос",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры",
                "текстуры"};

        public static String[] knowledgeAreas = {
                //Web
                "Engineering Management - Teamwork Understanding subordinates' and manager's expectations ",
                "Engineering Management - Teamwork Setting goals, SMART goals concept ",
                "Engineering Management - Teamwork Giving and receiving feedback ",
                "Engineering Management - Teamwork Reporting on task status ",
                "Engineering Management - Teamwork Providing feedback to team members ",
                "Engineering Management - Teamwork Tasks planning, delegation and tracking ",
                "Engineering Management - Teamwork Effective discussions (active listening, involving people, asking questions ) ",
                "Engineering Management - Teamwork Dealing with conflict ",
                "Engineering Management - Teamwork Team building ",
                "Engineering Management - Teamwork Creating development activities ",
                "Engineering Management - Teamwork Managing & participation in decision making (concluding, voting, asking 2-3 people to make a decision, asking manger to decide) ",
                "Engineering Management - Teamwork Coaching vs. mentoring, and other support roles: consultant, manager, instructor (guide) ",
                "Engineering Management - Teamwork Choosing between mentoring and coaching approaches ",
                "Engineering Management - Teamwork GROW model concept ",
                "Engineering Management - Teamwork Questioning",
                "Engineering Management - Teamwork Active listening ",
                "Engineering Management - Teamwork Feedback to coachee ",
                "Engineering Management - Process Planning (SDLC)Software development methodology ",
                "Engineering Management - Process Planning (SDLC)Basic SDLC models ",
                "Engineering Management - Process Planning (SDLC)Software Development Methodologies",
                "Engineering Management - Process Planning (SDLC)Abiliton SDLC ",
                "Engineering Management - Process Planning (SDLC)SCRUM-based SDLC models ",
                "Engineering Management - Process Planning (SDLC)RUP-based SDLC models ",
                "Engineering Management - Process Planning (SDLC)XP methodology ",
                "Engineering Management - Process Planning (SDLC)Engineering Process Planning",
                "Engineering Management - Process Planning (SDLC)Architecture design & evaluation ",
                "Engineering Management - Process Planning (SDLC)Unit testing ",
                "Engineering Management - Process Planning (SDLC)Defining code review procedures ",
                "Engineering Management - Process Planning (SDLC)Engineering Process Planning",
                "Engineering Management - Process Planning (SDLC)Deployment plan ",
                "Engineering Management - Process Planning (SDLC)Defining development environment tools suit",
                "Engineering Management - Process Planning (SDLC)Application security plan ",
                "Engineering Management - Process Planning (SDLC)Application performance plan ",
                "Engineering Management - Process Planning (SDLC)Defining performance testing strategy ",
                "Engineering Management - Estimation Scope Concept ",
                "Engineering Management - Estimation Work Break Down Structure ",
                "Engineering Management - Estimation WBS Based Effort Estimations ",
                "Engineering Management - Estimation Analogy-based estimations ",
                "Engineering Management - Estimation Documenting estimation results ",
                "Engineering Management - Estimation Delphi method ",
                "Engineering Management - Estimation Story based scope definition ",
                "Engineering Management - Estimation Story based estimations ",
                "Requirements - Software Requirements Requirements Management Fundamentals ",
                "Requirements - Software Requirements Requirements Classification ",
                "Requirements - Software Requirements Requirements Specification: Use Cases ",
                "Requirements - Software Requirements Requirements Specification: UML ",
                "Requirements - Software Requirements Requirements Specification: E/R ",
                "Requirements - Software Requirements Requirements Specification: SRS ",
                "Requirements - Software Requirements Requirements analysis, sources and stakeholders ",
                "Requirements - Software Requirements Requirements elicitation techniques ",
                "Requirements - Software Requirements Requirements organization ",
                "Requirements - Software Requirements Scope Management ",
                "Requirements - Software Requirements Requirements refinement ",
                "Requirements - Software Requirements Requirements validation ",
                "Requirements - Software Requirements Tracibility of requirements ",
                "Requirements - Software Requirements Requirements change management ",
                "Requirements - Software Requirements Requirements best practices and patterns ",
                "Design - OOD Abstraction",
                "Design - OOD Encapsulation",
                "Design - OOD Inheritance vs. Aggregation ",
                "Design - OOD Modularity",
                "Design - OOD Polymorphism",
                "Design - OOD Types vs. Classes ",
                "Design - OOD Abstraction Qualities (cohesion, coupling, etc) ",
                "Design - OOD GoF Design Patterns ",
                "Design - OOD Architectural Patterns: Layered Architecture ",
                "Design - OOD Architectural Patterns: MVC ",
                "Design - OOD Architectural Patterns: SOA and EDA ",
                "Design - OOD Architectural Patterns: IoC ",
                "Design - OOD Principles of Object Oriented Design  ",
                "Design - OOD Patterns of Enterprise Architecture Applications ",
                "Design - OOD Core J2EE Patterns (Java developers only)  ",
                "Design - OOD Architecture Qualities ",
                "Design - DB Design Relational terminology: Entities ",
                "Design - DB Design Relational terminology: Attributes ",
                "Design - DB Design Relational terminology: Records (Tuples) ",
                "Design - DB Design Relationships (One-to-One, One-to-Many) ",
                "Design - DB Design Understanding ER notation ",
                "Design - DB Design Understanding normalization concept ",
                "Design - DB Design Data Integrity ",
                "Design - DB Design Understanding RDBMS architecture ",
                "Design - DB Design Transactions: ACID ",
                "Design - DB Design Transactions: Recovery ",
                "Design - DB Design Transactions: Locking ",
                "Design - DB Design Transactions: Isolation ",
                "Design - DB Design Transactions: Concurrency ",
                "Design - DB Design Optimization database (performance, volume) ",
                "Design - Modeling UML: Basic Diagram Types ",
                "Design - Modeling UML: Use Case Diagram (Essentials) ",
                "Design - Modeling UML: Class Diagram (Essentials) ",
                "Design - Modeling Entity Relationship Diagrams ",
                "Design - Modeling Data Flow Diagrams ",
                "Design - Modeling UML: Structure Diagrams ",
                "Design - Modeling Class Diagram (Advanced) ",
                "Design - Modeling Component Diagram ",
                "Design - Modeling Composite Structures Diagram ",
                "Design - Modeling Package Diagram ",
                "Design - Modeling Deployment Diagram ",
                "Design - Modeling Object Diagram ",
                "Design - Modeling UML: Behavior Diagrams ",
                "Design - Modeling Activity Diagram ",
                "Design - Modeling Use Case Diagram (Advanced) ",
                "Design - Modeling State Diagram ",
                "Design - Modeling UML: Interaction Diagrams ",
                "Design - Modeling Sequence Diagram ",
                "Design - Modeling Communication Diagram ",
                "Security - Java Secure coding practices ",
                "Security - Java Platform Security (Strong data typing, Automatic memory management, Bytecode verification, Secure class loading) ",
                "Security - Java Authentication and Access Control ",
                "Security - Java Auxiliary Tools (keytool, policytool, jarsigner) ",
                "Security - Java Java Cryptography Architecture (JCA) API ",
                "Security - Java Code obfuscation ",
                "Security - Java Secure communications fundamentals (SSL, TSL, HTTPS, SASL) ",
                "Security - Java Basic access authentication (HTTP) ",
                "Security - Java WS-Security fundamentals ",
                "Security - Java Modelling threats ",
                "Security - Java Secure Communications (SSL, TSL, HTTPS, SASL) ",
                "Security - Java Access Protocol (SSO, LDAP) ",
                "Security - Java Protection against topmost critical Web-application security vulnerabilities ",
                "Security - Java JEE Security ",
                "Security - Java WS-Security ",
                "Construction - Language - Java Identifiers & JavaBeans ",
                "Construction - Language - Java Declare Classes ",
                "Construction - Language - Java Declare Interfaces ",
                "Construction - Language - Java Declare Class Members ",
                "Construction - Language - Java Reference Variable Casting ",
                "Construction - Language - Java Implementing an Interface ",
                "Construction - Language - Java Legal Return Types ",
                "Construction - Language - Java Constructors and Instantiation ",
                "Construction - Language - Java Statics",
                "Construction - Language - Java Stack and Heap ",
                "Construction - Language - Java Literals, Assignments, and Variables ",
                "Construction - Language - Java Passing Variables into Methods ",
                "Construction - Language - Java Array Declaration, Construction, and Initialization ",
                "Construction - Language - Java Java Operators ",
                "Construction - Language - Java if and switch Statements ",
                "Construction - Language - Java Loops and Iterators ",
                "Construction - Language - Java Handling Exceptions ",
                "Construction - Language - Java Common Exceptions and Errors ",
                "Construction - Language - Java String, StringBuilder, and StringBuffer ",
                "Construction - Language - Java Using the javac and java Commands ",
                "Construction - Language - Java Using Wrapper Classes and Boxing ",
                "Construction - Language - Java Overloading",
                "Construction - Language - Java Garbage Collection ",
                "Construction - Language - Java Working with the Assertion Mechanism ",
                "Construction - Language - Java File Navigation and I/O ",
                "Construction - Language - Java Dates, Numbers, and Currency ",
                "Construction - Language - Java Parsing,Tokenizing, and Formatting ",
                "Construction - Language - Java Overriding hashCode() and equals() ",
                "Construction - Language - Java Collections ",
                "Construction - Language - Java Using the Collections Framework ",
                "Construction - Language - Java Generic Types ",
                "Construction - Language - Java JAR Files ",
                "Construction - Language - Java Static Imports ",
                "Construction - Language - Java Serialization ",
                "Construction - Language - Java Inner Classes ",
                "Construction - Language - Java Method-Local Inner Classes ",
                "Construction - Language - Java Anonymous Inner Classes ",
                "Construction - Language - Java Static Nested Classes ",
                "Construction - Language - Java Defining, Instantiating, and Starting Threads ",
                "Construction - Language - Java Thread States and Transitions ",
                "Construction - Language - Java Synchronizing Code ",
                "Construction - Language - Java Thread Interaction ",
                "Construction - Language - Java Reflection",
                "Construction - Language - Java Annotations",
                "Construction - Language - Java Objects caching, and clustering ",
                "Construction - Language - Java Virtual Machine ",
                "Construction - Refactoring Refactoring Concept (what/when/why) ",
                "Construction - Refactoring Moving Features Between Objects (basic)",
                "Construction - Refactoring Move Method ",
                "Construction - Refactoring Move Field ",
                "Construction - Refactoring Organizing Data (basic)",
                "Construction - Refactoring  Encapsulate Field ",
                "Construction - Refactoring Encapsulate Collection ",
                "Construction - Refactoring Composing Methods (basic)",
                "Construction - Refactoring Extract Method ",
                "Construction - Refactoring Inline Method ",
                "Construction - Refactoring Inline Temp ",
                "Construction - Refactoring Replace Temp with Query ",
                "Construction - Refactoring Split Temporary Variable ",
                "Construction - Refactoring Simplifying Conditional Expressions (basic)",
                "Construction - Refactoring Decompose Conditional Expression ",
                "Construction - Refactoring Consolidate Conditional Expression ",
                "Construction - Refactoring Consolidate Duplicate Conditional Fragments ",
                "Construction - Refactoring Remove Control Flag ",
                "Construction - Refactoring Replace Conditional with Polymorphism ",
                "Construction - Refactoring Smells Catalog and possible refactoring ",
                "Construction - Refactoring Composing Methods ",
                "Construction - Refactoring Moving Features Between Objects ",
                "Construction - Refactoring Organizing Data ",
                "Construction - Refactoring Simplifying Conditional Expressions ",
                "Construction - Refactoring Making Method Calls Simpler ",
                "Construction - Refactoring Dealing with Generalization ",
                "Construction - Refactoring Refactoring to patterns ",
                "Construction - Concurrency - Java Thread Creation and Management ",
                "Construction - Concurrency - Java Data Synchronization ",
                "Construction - Concurrency - Java Thread Notification ",
                "Construction - Concurrency - Java Minimal Synchronization Techniques ",
                "Construction - Concurrency - Java Advanced Synchronization ",
                "Construction - Concurrency - Java Threads and Collection Classes ",
                "Construction - Concurrency - Java Thread Scheduling ",
                "Construction - Concurrency - Java Thread Pools ",
                "Construction - Concurrency - Java Task Scheduling ",
                "Construction - Concurrency - Java Threads and I/O ",
                "Construction - Distributed Objects and Components - Java Anatomy of a Distributed Application ",
                "Construction - Distributed Objects and Components - Java Requirements for Developing Distributed Application ",
                "Construction - Distributed Objects and Components - Java Distributed Objects In Java ",
                "Construction - Distributed Objects and Components - Java Java RMI ",
                "Construction - Distributed Objects and Components - Java Message Processing ",
                "Construction - Distributed Objects and Components - Java Object-Oriented Analysis and Design ",
                "Construction - Distributed Objects and Components - Java Java's Networking and Enterprise APIs ",
                "Construction - Distributed Objects and Components - Java CORBA ",
                "Construction - Distributed Objects and Components - Java Distributed Component Object Model (DCOM) ",
                "Construction - Networking - Java The Layers of a Network ",
                "Construction - Networking - Java Application Layer Protocols Basics ",
                "Construction - Networking - Java Understanding Networks - Layers and Protocols ",
                "Construction - Networking - Java IP, TCP, and UDP ",
                "Construction - Networking - Java The Client/Server Model ",
                "Construction - Networking - Java Internet Standards ",
                "Construction - Networking - Java HTML, SGML, and XML ",
                "Construction - Networking - Java HTTP",
                "Construction - Networking - Java MIME Media Types ",
                "Construction - Networking - Java Looking Up Internet Addresses ",
                "Construction - Networking - Java URLs and URIs ",
                "Construction - Networking - Java Sockets for Clients ",
                "Construction - Networking - Java Sockets for Servers",
                "Construction - Networking - Java UDP Datagrams and Sockets ",
                "Construction - Networking - Java URLConnections ",
                "Construction - SQL Tables, relationships, keys, constraints understanding ",
                "Construction - SQL DDL, DML, DCD understanding ",
                "Construction - SQL SQL data types ",
                "Construction - SQL SQL operators, functions ",
                "Construction - SQL Data manipulation (insert, update, delete) ",
                "Construction - SQL Retrieving data (simple select statement) ",
                "Construction - SQL Joins understanding ",
                "Construction - SQL Creating, modifying, removing database objects ",
                "Construction - SQL Aggregations (ORDER BY, GROUP BY, HAVING, SUM, COUNT, AVG, etc) ",
                "Construction - SQL Combining the results of multiple queries (union, except, intersect, minus, subqueries) ",
                "Construction - SQL Sessions, transactions, locks ",
                "Construction - SQL Implementing stored procedures, user-defined functions, triggers ",
                "Construction - SQL Cursors",
                "Construction - SQL Dynamic SQL ",
                "Construction - SQL Manage permissions (GRANT REVOKE) ",
                "Construction - SQL Data manipulation using updatable views ",
                "Construction - SQL System catalog (information schema) usage ",
                "Construction - DB Access - Java Working with Connection",
                "Construction - DB Access - Java Preparing and Executing SQL commands",
                "Construction - DB Access - Java DB access exceptions handling",
                "Construction - DB Access - Java Working with ResultSet",
                "Construction - DB Access - Java Hibernate: Understanding object/relational persistence",
                "Construction - DB Access - Java Hibernate: Introducing and integrating Hibernate",
                "Construction - DB Access - Java Hibernate: Mapping persistent classes",
                "Construction - DB Access - Java Hibernate: Working with persistent objects",
                "Construction - DB Access - Java Working with MetaData",
                "Construction - DB Access - Java Working with Rowset",
                "Construction - DB Access - Java Transactions. Data integrity",
                "Construction - DB Access - Java Connection pooling",
                "Construction - DB Access - Java Working with offline data",
                "Construction - DB Access - Java Handle special data types",
                "Construction - DB Access - Java JPA",
                "Construction - DB Access - Java Hibernate: Setting up an annotations project",
                "Construction - DB Access - Java Hibernate: Mapping with EJB3/JPA Annotations",
                "Construction - DB Access - Java Hibernate: Mapping Queries",
                "Construction - DB Access - Java Hibernate: Retrieving objects efficiently",
                "Construction - DB Access - Java Hibernate: Hibernate Annotation Extensions",
                "Construction - DB Access - Java Hibernate: Transactions, concurrency, and caching",
                "Construction - DB Access - Java Hibernate: Advanced mapping concepts",
                "Construction - DB Access - Java Hibernate: Using the toolset",
                "Verification - Code Quality - Java Code Conventions for the Java Programming Language ",
                "Verification - Code Quality - Java Automated coding standards enforcement (Check Style) ",
                "Verification - Code Quality - Java Code Reviews and Toolset (Jupiter) ",
                "Verification - Code Quality - Java Preemptive Error Detection (Find Bugs, PMD) ",
                "Verification - Code Quality - Java Cyclomatic Complexity ",
                "Verification - Code Quality - Java Chidamber and Kemerer Object-Oriented metrics ",
                "Verification - Code Quality - Java OOD Metrics ",
                "Verification - Code Quality - Java Quality Metrics Tools (JDepend, JavaNCSS, CKJM, Panopticode, etc) ",
                "Verification - Automated Testing - Java JUnit fundamentals and elementary tests ",
                "Verification - Automated Testing - Java Organizing and building JUnit tests ",
                "Verification - Automated Testing - Java Managing test suites ",
                "Verification - Automated Testing - Java Working with test data ",
                "Verification - Automated Testing - Java Running JUnit tests ",
                "Verification - Automated Testing - Java Reporting JUnit results ",
                "Verification - Automated Testing - Java Mocks/Stubs ",
                "Verification - Automated Testing - Java Code Coverage Tools and Metrics (EMMA/Cobertura) ",
                "Verification - Automated Testing - Java TestNG",
                "Verification - Automated Testing - Java Testing Web applications (HTTP Unit, StrutsTestCase, Selenium, etc) \t",
                "Verification - Automated Testing - Java Testing GUI applications(JFCUnit, Abbot, etc) ",
                "Verification - Automated Testing - Java Integration testing with databases (DBUnit) ",
                "Verification - Automated Testing - Java Testing concurrent programs ",
                "Verification - Automated Testing - Java Testing Web Services (soapUI) ",
                "Configuration Management - Builds Automated build concept ",
                "Configuration Management - Builds Building with build tool (ant, make, rake, ...), cleaning up built product ",
                "Configuration Management - Builds Scripting multiphase (build, testing, deployment, …) build process ",
                "Configuration Management - Builds Integrating building of product installer ",
                "Configuration Management - Builds Generating release notes and/or other release documentation ",
                "Configuration Management - Builds Development of scheduled builds (night builds) ",
                "Configuration Management - Builds Monitoring build process ",
                "Configuration Management - Builds Build status reporting (notification) ",
                "Configuration Management - Builds Integrating deployment stage, moving product to release area ",
                "Configuration Management - Builds Integrating with source control, versioning, tagging, building releases ",
                "Configuration Management - Builds Continuous integration concept, best practices and framework",
                "Configuration Management - VCS (Version Control Systems) Fundamental concepts: revisions, working copy, repository",
                "Configuration Management - VCS (Version Control Systems) Getting (checking out) data from repository",
                "Configuration Management - VCS (Version Control Systems) Examining local changes, comparing working copy to repository",
                "Configuration Management - VCS (Version Control Systems) Updating working copy, merging changes",
                "Configuration Management - VCS (Version Control Systems) Updating to specific version",
                "Configuration Management - VCS (Version Control Systems) Examining change history",
                "Configuration Management - VCS (Version Control Systems) Discarding changes",
                "Configuration Management - VCS (Version Control Systems) Resolving conflicts in code",
                "Configuration Management - VCS (Version Control Systems) Copying, moving files, folders in repository",
                "Configuration Management - VCS (Version Control Systems) Committing changes",
                "Configuration Management - VCS (Version Control Systems) Importing sources into repository",
                "Configuration Management - VCS (Version Control Systems) Exporting sources from repository",
                "Configuration Management - VCS (Version Control Systems) Comparing repository revisions",
                "Configuration Management - VCS (Version Control Systems) Creating a branch, tagging",
                "Configuration Management - VCS (Version Control Systems) Working with branch",
                "Configuration Management - VCS (Version Control Systems) Traversing branches",
                "Configuration Management - VCS (Version Control Systems) Common branching patterns",
                "Configuration Management - VCS (Version Control Systems) Merging branches",
                "Configuration Management - VCS (Version Control Systems) Creating and applying patches",
                "Configuration Management - VCS (Version Control Systems) Revision specifies",
                "Construction - Web UIJavaScript: Variables  ",
                "Construction - Web UI Javascript: Data types and types conversion ",
                "Construction - Web UI Javascript: Operators ",
                "Construction - Web UI Javascript: Control and Loop constructions ",
                "Construction - Web UI Javascript: Functions and Variables scopes ",
                "Construction - Web UI Javascript: Arrays ",
                "Construction - Web UI Javascript: Event Handling ",
                "Construction - Web UI DOM: Locating and modifying elements ",
                "Construction - Web UI HTML: Basic elements ",
                "Construction - Web UI CSS: Simple Style rules ",
                "Construction - Web UI Javascript: Event Understanding ( propagation, attach/detach) ",
                "Construction - Web UI HTML: Page Layouts with tables ",
                "Construction - Web UI HTML: Page Layouts with divs ",
                "Construction - Web UI HTML: Frames ",
                "Construction - Web UI HTML: Embedded multimedia ",
                "Construction - Web UI CSS: Elements positioning and layering ",
                "Construction - Web UI CSS: Tables properties ",
                "Construction - Web UI CSS: Complex rules and defining styles structure ",
                "Construction - Web UI XML: XmlDcoument ",
                "Construction - Web UI XML: XmlHttpRequest ",
                "Construction - Web UI AJAX: Consuming Webservices ",
                "Construction - Web UI AJAX: Understanding JSON ",
                "Construction - Web UI Web Browser: Cookies management ",
                "Construction - Web UI Javascript: Closures ",
                "Construction - Web UI Javascript: Objects ",
                "Construction - Web UI Javascript: Regular Expressions ",
                "Construction - Web UI Javascript: Scripting security ",
                "Construction - Web UI HTML: Standards and Browser compatibility ",
                "Construction - Web UI CSS: For different media (printing, mobile etc.) ",
                "Construction - Web UI Web Browser: performance optimization ",
                "Construction - Web UI Web Browser: Memory management and optimization ",
                "Construction - Web server applications - Java An Overview of Servlet and JSP Technology ",
                "Construction - Web server applications - Java Server Setup and Configuration ",
                "Construction - Web server applications - Java Servlet Basics ",
                "Construction - Web server applications - Java Handling the Client Request: Form Data ",
                "Construction - Web server applications - Java Invoking Java Code with JSP Scripting Elements ",
                "Construction - Web server applications - Java Session Tracking ",
                "Construction - Web server applications - Java Integrating Servlets and JSP: The Model View Controller (MVC) Architecture ",
                "Construction - Web server applications - Java XML Basics ",
                "Construction - Web server applications - Java The W3C XML Schema Language ",
                "Construction - Web server applications - Java Handling the Client Request: HTTP Request Headers ",
                "Construction - Web server applications - Java Generating the Server Response: HTTP Status Codes ",
                "Construction - Web server applications - Java Generating the Server Response: HTTP Response Headers",
                "Construction - Web server applications - Java Handling Cookies ",
                "Construction - Web server applications - Java JAXP: SAX2 / DOM ",
                "Construction - Web server applications - Java Web Services fundamentals (concept, SOAP, REST, WSDL, etc) ",
                "Construction - Web server applications - Java Controlling the Structure of Generated Servlets: The JSP page Directive ",
                "Construction - Web server applications - Java Including Files and Applets in JSP Pages ",
                "Construction - Web server applications - Java Using JavaBeans Components in JSP Documents ",
                "Construction - Web server applications - Java The JSP 2.0 Expression Language ",
                "Construction - Web server applications - Java JSP Standard Tag Library (JSTL) ",
                "Construction - Web server applications - Java Using and Deploying Web Applications ",
                "Construction - Web server applications - Java Controlling Web Application Behavior with web.xml ",
                "Construction - Web server applications - Java Servlet and JSP Filters ",
                "Construction - Web server applications - Java The Application Events Framework ",
                "Construction - Web server applications - Java Tag Libraries: The Basics ",
                "Construction - Web server applications - Java MVC: at least one of Spring MVC/Struts/Tapestry/Wicket/GWT/etc ",
                "Construction - Web server applications - Java IoC: at least one of Spring/Google Guice/etc ",
                "Construction - Web server applications - Java JAX-WS 2.0 ",
                "Construction - Web server applications - Java Apache Axis ",
                "Construction - Web server applications - Java Spring WS ",
                "Construction - Web server applications - Java Xfire ",
                "Construction - Web server applications - Java JavaMail",
                "Construction - Web server applications - Java Declarative and programmatic security ",
                "Construction - Web server applications - Java Tag Libraries: Advanced Features ",
                "Construction - Web server applications - Java JMS",
                "Construction - Web server applications - Java Core J2EE Patterns ",
                "Construction - Web server applications - Java Major Web frameworks internals (Spring, etc) ",
                //Other
//                "Construction - Desktop applications - Java Getting Started with Swing",
//                "Construction - Desktop applications - Java Learning Swing with the NetBeans IDE",
//                "Construction - Desktop applications - Java Using Swing Components",
//                "Construction - Desktop applications - Java Concurrency in Swing",
//                "Construction - Desktop applications - Java Laying Out Components Within a Container",
//                "Construction - Desktop applications - Java Writing Event Listeners",
//                "Construction - Desktop applications - Java Using Other Swing Features (actions, timers, and the system tray, etc.)",
//                "Construction - Desktop applications - Java Modifying the Look and Feel",
//                "Construction - Desktop applications - Java Drag and Drop and Data Transfer",
//                "Construction - Desktop applications - Java Performing Custom Painting",
//                "Construction - Desktop applications - Java Overview of the Java 2D API Concepts",
//                "Construction - Desktop applications - Java Getting Started with Graphics Working with Geometry ",
//                "Construction - Desktop applications - Java Working with Text APIs ",
//                "Construction - Desktop applications - Java Working with Images ",
//                "Construction - Desktop applications - Java Printing ",
//                "Construction - Desktop applications - Java Advanced Topics in Java2D ",
//                "Construction - Desktop applications - Java Design Guidelines: The Java Look and Feel",
//                "Construction - Desktop applications - Java Design Guidelines: The Java Foundation Classes",
//                "Construction - Desktop applications - Java Design Guidelines: Design Considerations",
//                "Construction - Desktop applications - Java Design Guidelines: Visual Design",
//                "Construction - Desktop applications - Java Design Guidelines: Application Graphics",
//                "Construction - Desktop applications - Java Design Guidelines: Behavior",
//                "Construction - Desktop applications - Java Design Guidelines: Windows and Panes",
//                "Construction - Desktop applications - Java Design Guidelines: Dialog Boxes and Alert Boxes",
//                "Construction - Desktop applications - Java Design Guidelines: Menus and Toolbars",
//                "Construction - Desktop applications - Java Design Guidelines: Basic Controls",
//                "Construction - Desktop applications - Java Design Guidelines: Text Components",
//                "Construction - Desktop applications - Java Design Guidelines: Selectable Lists, Tables, and Tree Components",
//                "Construction-Web Services-Java Web Services Platform Architecture ",
//                "Construction-Web Services-Java SOAP Web Services fundamentals ",
//                "Construction-Web Services-Java RESTful Web Services fundamentals (REST definition, 5 main principles of REST, working with RESTful Web Services) ",
//                "Construction-Web Services-Java WSDL fundamentals ",
//                "Construction-Web Services-Java SOAP Handlers ",
//                "Construction-Web Services-Java SOAP Web Services Advanced (WSDL generation from source code, namespaces, defining Web Service operations, return types, etc) ",
//                "Construction-Web Services-Java RESTful Web Services Advanced (REST vs. SOAP, different resource representation, accessing query parameters) ",
//                "Construction-Web Services-Java JAX-WS Annotations ",
//                "Construction-Web Services-Java JAX-WS Client-Side Development ",
//                "Construction-Web Services-Java JAX-WS Server-Side Development ",
//                "Construction-Web Services-Java JAXR",
//                "Construction-Web Services-Java JAX-RS ",
//                "Construction-Web Services-Java Web Services Packaging and Deployment ",
//                "Construction-Web Services-Java UDDI",
//                "Construction-Web Services-Java Web Services with SAAJ ",
//                "Construction-Web Services-Java Ajax and Java Web Services ",
//                "Construction-Web Services-Java RESTful Web Services implementation (at least one):",
//                "Construction-Web Services-Java CXF",
//                "Construction-Web Services-Java Jersey",
//                "Construction-Web Services-Java Restlet",
//                "Construction-Web Services-Java RESTEasy",
//                "Construction-Web Services-Java Web Services Security (SOAP, RESTful) ",
//                "Construction-Web Services-Java Web Services Quality of Service ",
//                "Construction-Web Services-Java Web Services Interoperability ",
//                "Construction-Web Services-Java Web Services Design Patterns and Antipatterns ",
//                "Construction-Web Services-Java Web Service Monitoring ",
//                "Construction-SOA-Java Definition and concepts of SOA ",
//                "Construction-SOA-Java The role of services in SOA ",
//                "Construction-SOA-Java Loose coupling (Reduce dependencies between different systems). ",
//                "Construction-SOA-Java Services classification ",
//                "Construction-SOA-Java ESB responsibility and role in SOA ",
//                "Construction-SOA-Java Principles of Service Orchestrations with BPEL ",
//                "Construction-SOA-Java Messaging Key principles ",
//                "Construction-SOA-Java SOA Architecture Models ",
//                "Construction-SOA-Java Message Exchange Patterns ",
//                "Construction-SOA-Java Service lifecycle ",
//                "Construction-SOA-Java  Idempotency, State and Stateless Services ",
//                "Construction-SOA-Java  ESB architecture and components ",
//                "Construction-SOA-Java Understanding message flows ",
//                "Construction-SOA-Java Implement integration logic (ESB logging, custom transformers )  ",
//                "Construction-SOA-Java Working with messages (routing, validation, transforming messages) ",
//                "Construction-SOA-Java Connectivity",
//                "Construction-SOA-Java Supporting web services (hosting, consuming, ws-security and ws-addressing) ",
//                "Construction-SOA-Java Service orchestration with BPEL ",
//                "Construction-SOA-Java  Implementing a process engine with jBPM ",
//                "Construction-SOA-Java Security",
//                "Construction-SOA-Java Performance",
//                "Construction-SOA-Java Versioning",
//                "Construction-SOA-Java Governance",
//                "Construction-SOA-Java Enterprise quality message flows (error handling, LDAP, Acegi) ",
//                "Construction-SOA-Java Overview of the Enterprise Integration patterns ",
//                "Construction-SOA-Java Implementing a process engine with jBPM  ",
//                "Construction-SOA-Java Advanced activities and features of jBPM ",
//                "Android Installing SDK ",
//                "Android Installing ADP plug-in for eclipse ",
//                "Android Android tools from SDK ",
//                "Android Running on Emulator ",
//                "Android Debugging",
//                "Android Application Components ",
//                "Android Activity, Processes and Threads ",
//                "Android Component Lifecycle ",
//                "Android Organizing Source Files ",
//                "Android Application Private Storage ",
//                "Android Signing & Versioning ",
//                "Android View Hierarchy & Layout ",
//                "Android Activities, Intent & Filters ",
//                "Android UI Controls, UI Events ",
//                "Android Search",
//                "Android Menus",
//                "Android Dialogs, User notification ",
//                "Android Resource Types (Drawable, Layout, Menu, String) ",
//                "Android Handling Runtime Changes ",
//                "Android Localization",
//                "Android Providing & Accessing Resources",
//                "Android Using Shared Preferences ",
//                "Android PreferenceActivity ",
//                "Android Internal Storage (Device Memory) ",
//                "Android External Storage (SD Card) ",
//                "Android Using Permissions ",
//                "Android Declaring and Enforcing Permissions ",
//                "Android Determining network status ",
//                "Android Using the network to retrieve and store data ",
//                "Android Working with web services ",
//                "Android Adapters & Data binding ",
//                "Android Styles and Themes ",
//                "Android Building Custom Components ",
//                "Android Widgets",
//                "Android Web View, Web applications ",
//                "Android 2D Graphics and Animation ",
//                "Android Handling multitouch and gestures (zoom, drag) ",
//                "Android Icon Design Guidelines ",
//                "Android Widget Design Guidelines ",
//                "Android Menu Design Guidelines ",
//                "Android Designing for Performance ",
//                "Android Designing for Responsiveness ",
//                "Android Services, Lifecycle ",
//                "Android Broadcast Receivers, Lifecycle ",
//                "Android AsyncTask and the UI thread ",
//                "Android Persistence - Advanced ",
//                "Android SQLite Database ",
//                "Android Content Providers ",
//                "Android Data Backup ",
//                "Android Authentication",
//                "Android URI Permissions ",
//                "Android Obtaining User Location ",
//                "Android Google Maps ",
//                "Android Making and receiving phone calls ",
//                "Android Capturing call-related events ",
//                "Android Obtaining phone and service information ",
//                "Android Using SMS ",
//                "Android Audio and Video Playback ",
//                "Android Playing from a Raw Resource ",
//                "Android Playing from a File or Stream ",
//                "Android Audio Capture ",
//                "Android 3D graphics with OpenGL",
//                "Android Camera",
//                "Android Bluetooth",
//                "Android Sensors",
//                "Android Synchronization",
//                "Android Device Administration ",
//                "Android Licensing & Preparing to Publish ",
//                "Android Publish",
//                "Android JNI and Android ",
//                "Android Implementing/Calling native methods using JNI ",
//                "Android Android provided native libraries ",
//                "Android Building your own custom library modules ",
//                "Android Native Activities  ",
//                "Construction - Networking - Basic knowledge of physical layer protocols and media ",
//                "Construction - Networking - Understanding HTTP and WWW ",
//                "Construction - Networking - Basic troubleshooting tools (ICMP, ping, traceroute) ",
//                "Construction - Networking - Sockets, IP and port addressing ",
//                "Construction - Networking - Using proxy server ",
//                "Construction - Networking - File transfer services: FTP, TFTP ",
//                "Construction - Networking - Name resolution services: DNS, whois ",
//                "Construction - Networking - Remote access services: Telnet, SSH, rdesktop, VNC ",
        };
    }
}
