package testpackage;

import testpackage.content.repetition.RandomTimeGenerator;

/**
 * User: mtitov Date: 10/31/11 Time: 1:48 PM
 */
public class RandomTimeGeneratorLauncher {

	public static void main(String[] args) {
		// final Calendar calendar = GregorianCalendar.getInstance();
		// calendar.set(Calendar.HOUR_OF_DAY, 12);
		// calendar.set(Calendar.MINUTE, 0);
		// System.out.println(calendar.getTime());
		// final long start = calendar.getTimeInMillis();
		// calendar.set(Calendar.HOUR_OF_DAY, 17);
		// System.out.println(calendar.getTime());
		// final long end = calendar.getTimeInMillis();
		// RandomTimeGenerator.printRandomTime(1, start, end);
		// RandomTimeGenerator.printSleepingTime();
		RandomTimeGenerator.printFixedWorkingDayRandomTimeFromNow(1);
		// RandomTimeGenerator.printRandomTime(1);

	}

	/**
	 * 3 - 4 years
	 */
	public static String[]	javaWebDesktopAndroidIntegration	= {
			"Exigen:P0:Java:Declare Classes: Source file declaration",
			"Exigen:P0:Java:Declare Classes: Class declarations and modifiers",
			"Exigen:P0:Java:Declare interfaces: Declare interfaces",
			"Exigen:P0:Java:Declare class members: Access modifiers",
			"Exigen:P0:Java:Declare class members: Constructor declarations",
			"Exigen:P0:Java: If and switch statements",
			"Exigen:P0:Java:Loops and Iterators: while, do and for loops",
			"Exigen:P0:Java:Loops and Iterators: break and continue",
			"Exigen:P0:Java:Handling exceptions: using try and catch",
			"Exigen:P0:Java:Handling exceptions: using finally",
			"Exigen:P0:Java:Handling exceptions: propagating uncaught exception",
			"Exigen:P0:Java:Handling exceptions: common exception types (checked and unchecked)",
			"Exigen:P0:OOP && OOD:Basic OOP concepts: polymorphism",
			"Exigen:P0:OOP && OOD:Basic OOP concepts: inheritance",
			"Exigen:P0:OOP && OOD:Basic OOP concepts: incapsulation",
			"Exigen:P1:Java:JavaBean definition",
			"Exigen:P1:Java:Declare interfaces:Implicit modifiers of interface members",
			"Exigen:P1:Java:Declaring enums",
			"Exigen:P1:Java:Overriding/Overloading",
			"Exigen:P1:Java:Constructors and Instantiation:Order of initialization/calling of fields and constructors",
			"Exigen:P1:Java:Constructors and Instantiation:Constructor overloading",
			"Exigen:P1:Java:Using Wrapper classes and boxing:Intention of wrapping objects",
			"Exigen:P1:Java:Using Wrapper classes and boxing:Creation wrapping objects",
			"Exigen:P1:Java:Using Wrapper classes and boxing:Autoboxing",
			"Exigen:P1:Java:Handling exceptions:exception matching and declaration",
			"Exigen:P1:Java:Passing variables into methods",
			"Exigen:P1:Java:String, StringBuilder and StringBuffer",
			"Exigen:P1:Java:Overriding hashCode and equals",
			"Exigen:P1:Java:Collections:Collection",
			"Exigen:P1:Java:Collections:List interface",
			"Exigen:P1:Java:Collections:Set interface",
			"Exigen:P1:Java:Collections:Map interface",
			"Exigen:P1:Java:Using collections API:ArrayList",
			"Exigen:P1:Java:Using collections API:HashMap",
			"Exigen:P1:Java:Generic types:Generics and legacy code",
			"Exigen:P1:Java:Generic types:Generics declarations",
			"Exigen:P1:Java:Inner classes:coding a regular inner class",
			"Exigen:P1:Java:Anonymous inner classes",
			"Exigen:P1:Java:Static inner classes:Instantiation and using",
			"Exigen:P1:Java:Static inner classes:access to outer class instance fields",
			"Exigen:P1:Java:Garbage Collection:Definition of grabage collection and garbage collector",
			"Exigen:P1:Unit testing:Purpose of unit tests",
			"Exigen:P1:Unit testing:JUnit 4:Setup and tear down",
			"Exigen:P1:Unit testing:JUnit 4:Exception handling",
			"Exigen:P1:Unit testing:JUnit 4:Asserts",
			"Exigen:P1:OOP && OOD:Separation of concerns",
			"Exigen:P2:Java:Garbage Collection:finalize",
			"Exigen:P2:Java:Serialization",
			"Exigen:P2:Java:Dates, Numbers and Currency",
			"Exigen:P2:Java:String Formatting",
			"Exigen:P2:Java:Collections:Collections and Arrays",
			"Exigen:P2:Java:Using collections API:LinkedList",
			"Exigen:P2:Java:Generic types:Polymorphism and generics",
			"Exigen:P2:Java:Generic types:Generics methods",
			"Exigen:P2:Java:Inner classes:reference outer instance from within inner class",
			"Exigen:P2:Java:Method local inner classes:local method variables in inner classes",
			"Exigen:P2:Spring:Bean Overview:Naming beans",
			"Exigen:P2:Spring:Dependencies:Dependency injection(setter , constructor and so on)",
			"Exigen:P2:Spring:Dependencies and configuration in detail:Straight values",
			"Exigen:P2:Spring:Dependencies and configuration in detail:Refrences to another beans",
			"Exigen:P2:Spring:Dependencies and configuration in detail:Inner beans",
			"Exigen:P2:Spring:Dependencies and configuration in detail:Collections",
			"Exigen:P2:Spring:Dependencies and configuration in detail:Lazy initialized beans",
			"Exigen:P2:Spring:Dependencies and configuration in detail:Method injection",
			"Exigen:P2:Spring:Bean scopes:singleton",
			"Exigen:P2:Spring:Bean scopes:prototype",
			"Exigen:P2:Spring:Bean scopes:request",
			"Exigen:P2:Spring:Bean scopes:session",
			"Exigen:P2:Spring:Bean scopes:scoped beans (session, request, prototype) as dependencies",
			"Exigen:P2:Spring:Annotation based configuration:Required",
			"Exigen:P2:Spring:Annotation based configuration:Autowired",
			"Exigen:P2:Spring:Class path scanning and managed components:Component and other stereotype annotations",
			"Exigen:P2:Spring:Class path scanning and managed components:Naming auto detected components",
			"Exigen:P2:Spring:Class path scanning and managed components:Providing scope for auto detected components",
			"Exigen:P2:Spring:Spring 3 field formatting:Annotation Driven Formatting",
			"Exigen:P2:Spring:Spring 3 Validation:Configuring bean validation implementation",
			"Exigen:P2:Spring:Spring 3 Validation:Spring MVC 3 Validation",
			"Exigen:P2:Spring:Integration testing:Context management and caching",
			"Exigen:P2:Spring:Integration testing:Dependency injection of text fixtures",
			"Exigen:P2:Spring:Integration testing:Transaction managament",
			"Exigen:P2:Spring:Integration testing:JUnit support",
			"Exigen:P2:Spring:Declarative transaction managament:Understending Spring declarative implementation model",
			"Exigen:P2:Spring:Declarative transaction managament:Rolling back declarative transaction",
			"Exigen:P2:Spring:Declarative transaction managament:@Transactional and its settings",
			"Exigen:P2:Spring:Declarative transaction managament:Transaction propagation levels",
			"Exigen:P2:Spring:JPA DAO support:LocalContainerEntityManagerFactoryBean",
			"Exigen:P2:Spring:JPA DAO support:Transaction Managament",
			"Exigen:P2:Spring:Web MVC Framework:DispatcherServlet and request lifecycle",
			"Exigen:P2:Spring:Web MVC Framework:mvc:annotation-driven",
			"Exigen:P2:Spring:Web MVC Framework:Defining controller with @Controller",
			"Exigen:P2:Spring:Web MVC Framework:Mapping requests with @RequestsMapping",
			"Exigen:P2:Spring:Web MVC Framework:Parameters and returns of @RequestMapping methods",
			"Exigen:P2:Spring:Web MVC Framework:URI templates",
			"Exigen:P2:Spring:Web MVC Framework:@RequestBody",
			"Exigen:P2:Spring:Web MVC Framework:@ResponseBody",
			"Exigen:P2:Spring:Web MVC Framework:@ModelAttribute",
			"Exigen:P2:Spring:Web MVC Framework:@SessionAttributes",
			"Exigen:P2:Spring:Web MVC Framework:@RequestHeader",
			"Exigen:P2:Spring:Web MVC Framework:@CookieValue",
			"Exigen:P2:Spring:Resolving views:ViewResolver",
			"Exigen:P2:Spring:Resolving views:redirect:",
			"Exigen:P2:Spring:Resolving views:forward:",
			"Exigen:P2:Spring:Spring multipart support",
			"Exigen:P2:Spring:Handling exceptions:@ExceptionHandler",
			"Exigen:P2:Spring:REST:General principles",
			"Exigen:P2:Spring:REST:RestTemplate",
			"Exigen:P2:Spring:REST:HttpMessage conversion",
			"Exigen:P2:Spring:REST:Spring MVC support",
			"Exigen:P2:Unit Testing:Difference between unit and integration tests (pros and cons)",
			"Exigen:P2:Unit Testing:TDD concepts:Development style",
			"Exigen:P2:Unit Testing:TDD concepts:Benefits",
			"Exigen:P2:Unit Testing:Mocks concept",
			"Exigen:P2:Unit Testing:JUnit 4:Timeout",
			"Exigen:P2:Unit Testing:JUnit 4:Ignore",
			"Exigen:P2:SVN:Advanced concepts:tag",
			"Exigen:P2:SVN:Advanced concepts:branch",
			"Exigen:P2:SVN:Advanced commands:merge",
			"Exigen:P2:SVN:Advanced commands:patch",
			"Exigen:P2:OOP && OOD:Purpose of OOP",
			"Exigen:P2:OOP && OOD:Coupling and Cohesion",
			"Exigen:P2:OOP && OOD:Information expert (GRASP)",
			"Exigen:P2:OOP && OOD:Interface segregation principle",
			"Exigen:P2:OOP && OOD:Single responsibility principle",
			"Exigen:P2:OOP && OOD:Examples of usage interfaces and abstract classes",
			"Exigen:P2:OOP && OOD:Dependency Inversion",
			"Exigen:P2:OOP && OOD:Open/Closed Principle",
			"Exigen:P2:OOP && OOD:Composite Reuse",
			"Exigen:P2:OOP && OOD:Acyclic Dependencies Principle",
			"Exigen:P2:OOP && OOD:Immutability",
			"Exigen:P2:OOP && OOD:GOF Patterns:Why we need patterns",
			"Exigen:P2:OOP && OOD:GOF Patterns:At least three from each category",
			"Exigen:P2:OOP && OOD:GOF Patterns:Examples from JDK (at least 3)",
			"Exigen:P2:JPA:ORM definition and purpose",
			"Exigen:P2:JPA:OR mapping:Entity definition",
			"Exigen:P2:JPA:OR mapping:Access entity state",
			"Exigen:P2:JPA:OR mapping:Mapping to table",
			"Exigen:P2:JPA:OR mapping:Mapping simple types",
			"Exigen:P2:JPA:OR mapping:Column mapping",
			"Exigen:P2:JPA:OR mapping:Enumerations",
			"Exigen:P2:JPA:OR mapping:Temporal types",
			"Exigen:P2:JPA:OR mapping:Id generation",
			"Exigen:P2:JPA:OR mapping:Relationship types",
			"Exigen:P2:JPA:OR mapping:One to many - primary key mappings",
			"Exigen:P2:JPA:OR mapping:Supported collection types",
			"Exigen:P2:JPA:OR mapping:OrderBy for List",
			"Exigen:P2:JPA:OR mapping:MapKey for Map",
			"Exigen:P2:JPA:OR mapping:Lazy loading",
			"Exigen:P2:JPA:Entity Manager:persist",
			"Exigen:P2:JPA:Entity Manager:find",
			"Exigen:P2:JPA:Entity Manager:remove",
			"Exigen:P2:JPA:Entity Manager:cascading options",
			"Exigen:P2:JPA:Entity Manager:detachment and merge",
			"Exigen:P2:JPA:JPQL:select",
			"Exigen:P2:JPA:JPQL:filtering results",
			"Exigen:P2:JPA:JPQL:projections",
			"Exigen:P2:JPA:JPQL:aggregate queries",
			"Exigen:P2:JPA:JPQL:query parameters",
			"Exigen:P2:JPA:JPQL:dynamic query definition",
			"Exigen:P2:JPA:JPQL:named query",
			"Exigen:P2:JPA:JPQL:query paging",
			"Exigen:P2:JPA:Locking:Optimistic locking",
			"Exigen:P2:Maven:Default configuration:Directory layout",
			"Exigen:P2:Maven:Default configuration:One primary output per project",
			"Exigen:P2:Maven:Plugins:Knowledge of what plug-ins there are",
			"Exigen:P2:Maven:Plugins:Configuring a plugin",
			"Exigen:P2:Maven:Plugins:Binding plugin goals to lifecycle phases",
			"Exigen:P2:Maven:Repositories:Local and remote repos",
			"Exigen:P2:Maven:Repositories:SNAPSHOTs vs regular versions",
			"Exigen:P2:Maven:Dependency managament:Transitive dependencies",
			"Exigen:P2:Maven:Dependency managament:How to exclude unwanted transitive dependencies",
			"Exigen:P2:Maven:Dependency managament:Different scopes and when to use them",
			"Exigen:P2:Maven:Dependency managament:Using dependencyManagement to share dependencies",
			"Exigen:P2:Maven:Build Lifecycle:different phases",
			"Exigen:P2:SQL:Table structure:schema",
			"Exigen:P2:SQL:Table structure:table",
			"Exigen:P2:SQL:Table structure:row",
			"Exigen:P2:SQL:Table structure:column",
			"Exigen:P2:SQL:Table structure:primary key",
			"Exigen:P2:SQL:Table structure:foreign key",
			"Exigen:P2:SQL:SQL select:like, in, between",
			"Exigen:P2:SQL:SQL select:aggregate queries",
			"Exigen:P2:SQL:SQL select:order by",
			"Exigen:P2:SQL:SQL select:distinct or count(distinct)",
			"Exigen:P2:SQL:SQL select:joins",
			"Exigen:P2:SQL:SQL select:difference between where and having",
			"Exigen:P2:SQL:SQL insert/update/delete",
			"Exigen:P2:SQL:Nulls",
			"Exigen:P3:Java:Garbage Collection:Cyclic dependencies",
			"Exigen:P3:Java:Handling exceptions:exceptions vs. error codes. Why exceptions were introduced in language.",
			"Exigen:P3:Java:Defining instantiating and starting  threads",
			"Exigen:P3:Java:Synchronizing code",
			"Exigen:P3:Java:Thread interaction:Wait and notify methods",
			"Exigen:P3:Spring:Dependencies and configuration in detail:Autowiring collabarators",
			"Exigen:P3:Spring:Customizing  the bean nature:Life cycle callbacks",
			"Exigen:P3:Spring:Customizing  the bean nature:ApplicationContextAware and BeanNameAware",
			"Exigen:P3:Spring:Bean definition inheritance",
			"Exigen:P3:Spring:Container extension point:BeanPostProcessor",
			"Exigen:P3:Spring:Container extension point:BeanFactoryPostProcessor",
			"Exigen:P3:Spring:Container extension point:FactoryBean",
			"Exigen:P3:Spring:Annotation based configuration:Fine tuning of autowiring",
			"Exigen:P3:Spring:Annotation based configuration:@Resource",
			"Exigen:P3:Spring:Annotation based configuration:PostConstruct and PreDestroy",
			"Exigen:P3:Spring:Class path scanning and managed components:Using filters",
			"Exigen:P3:Spring:Class path scanning and managed components:Defining bean metadata",
			"Exigen:P3:Spring:Resources:Resource interface",
			"Exigen:P3:Spring:Resources:Resource loader",
			"Exigen:P3:Spring:Resources:ResourceLoaderAware interface",
			"Exigen:P3:Spring:Resources:Resources as dependeincies",
			"Exigen:P3:Spring:Spring 3 field formatting:Formatter SPI",
			"Exigen:P3:Spring:Spring 3 field formatting:FormatterRegistry",
			"Exigen:P3:Spring:Spring AOP:AOP concepts",
			"Exigen:P3:Spring:Spring AOP:Spring AOP capabilities",
			"Exigen:P3:Spring:@AspectJ support:Enabling @AspectJ support",
			"Exigen:P3:Spring:@AspectJ support:Declaring Aspect",
			"Exigen:P3:Spring:@AspectJ support:Declaring pointcut",
			"Exigen:P3:Spring:@AspectJ support:Declaring advice",
			"Exigen:P3:Spring:@AspectJ support:Introductions",
			"Exigen:P3:Spring:Schema based AOP support:Declaring aspect",
			"Exigen:P3:Spring:Schema based AOP support:Declaring pointcut",
			"Exigen:P3:Spring:Schema based AOP support:Declaring advice",
			"Exigen:P3:Spring:Schema based AOP support:Introductions",
			"Exigen:P3:Spring:Configuring AspectJ aspects with Spring",
			"Exigen:P3:Spring:Transaction managament:Global transactions",
			"Exigen:P3:Spring:Transaction managament:Local transactions",
			"Exigen:P3:Spring:JPA DAO support:Consistent transaction model",
			"Exigen:P3:Spring:JPA DAO support:LocalEntityManagerFactoryBean",
			"Exigen:P3:Spring:JPA DAO support:JpaDialect and JpaVendorAdapter",
			"Exigen:P3:Spring:Web MVC Framework:WebDataBander initialization",
			"Exigen:P3:Spring:Web MVC Framework:Intercepting requests",
			"Exigen:P3:Spring:Resolving views:Chaining view resolvers",
			"Exigen:P3:Spring:Using locales",
			"Exigen:P3:Spring:Handling exceptions:HandlerExceptionResolver",
			"Exigen:P3:Spring:Velocity:context configuration",
			"Exigen:P3:Spring:Velocity:creating templates",
			"Exigen:P3:Spring:Velocity:advanced configuration",
			"Exigen:P3:Spring:Velocity:simple binding",
			"Exigen:P3:Spring:Velocity:form input generation",
			"Exigen:P3:Spring:Spring RMI:Hessian and Burlap support",
			"Exigen:P3:Spring:Spring RMI:HttpInvoker",
			"Exigen:P3:Spring:Spring RMI:JMS",
			"Exigen:P3:Spring:JMX:Exporting beans",
			"Exigen:P3:Spring:JMX:Controlling management interface",
			"Exigen:P3:Spring:JMX:Controlling object names",
			"Exigen:P3:Unit testing:TDD concepts:Vulnerabilities",
			"Exigen:P3:Unit testing:JUnit 4:Run With",
			"Exigen:P3:SVN:Advanced concepts:properties",
			"Exigen:P3:SVN:Advanced commands:switch",
			"Exigen:P3:OOP && OOD:Pure Fabrication (GRASP)",
			"Exigen:P3:OOP && OOD:ADT",
			"Exigen:P3:OOP && OOD:Liskov substitution and design by contract:definition of Liskov substitution",
			"Exigen:P3:OOP && OOD:Liskov substitution and design by contract:class invariant",
			"Exigen:P3:OOP && OOD:Liskov substitution and design by contract:input parameters constraints",
			"Exigen:P3:OOP && OOD:Liskov substitution and design by contract:returned results constraints",
			"Exigen:P3:OOP && OOD:Acyclic Dependencies Principle",
			"Exigen:P3:JPA:OR mapping:LOB and CLOB",
			"Exigen:P3:JPA:OR mapping:Transient state",
			"Exigen:P3:JPA:OR mapping:One to many - using join table",
			"Exigen:P3:JPA:OR mapping:Many to Many - using join table",
			"Exigen:P3:JPA:Entity Manager:transaction view",
			"Exigen:P3:JPA:JPQL:queries and uncommitted changes",
			"Exigen:P3:JPA:JPQL:bulk update and delete",
			"Exigen:P3:JPA:JPQL:query hints",
			"Exigen:P3:JPA:JPQL:best practices - hints, bulk delete, named queries",
			"Exigen:P3:JPA:Advanced ORM:Embedded objects",
			"Exigen:P3:JPA:Advanced ORM:Sharing embedded objects",
			"Exigen:P3:JPA:Advanced ORM:Compound primary key",
			"Exigen:P3:JPA:Advanced ORM:Embedded Id",
			"Exigen:P3:JPA:Advanced ORM:Read only mapping",
			"Exigen:P3:JPA:Advanced ORM:Optionality",
			"Exigen:P3:JPA:Advanced ORM:Compound join columns",
			"Exigen:P3:JPA:Advanced ORM:Multiple tables",
			"Exigen:P3:JPA:Advanced ORM:Inheritance models",
			"Exigen:P3:JPA:Advanced ORM:Transient classes",
			"Exigen:P3:JPA:Life cycle callbacks:Life cycle events",
			"Exigen:P3:JPA:Life cycle callbacks:Callback methods",
			"Exigen:P3:JPA:Life cycle callbacks:Listeners",
			"Exigen:P3:JPA:Life cycle callbacks:Attaching listeners to entities",
			"Exigen:P3:JPA:Life cycle callbacks:Listeners and inheritanse",
			"Exigen:P3:JPA:Refreshing entity state",
			"Exigen:P3:JPA:Locking:Read locking",
			"Exigen:P3:JPA:Locking:Write locking",
			"Exigen:P3:Maven:Profiles:Locations for profile definitions",
			"Exigen:P3:Maven:Profiles:What can be put into profile",
			"Exigen:P3:Maven:Profiles:Triggers for enabling profiles",
			"Exigen:P3:Maven:Build Lifecycle:Link between lifecycle and packaging",
			"Exigen:P3:Maven:Build Lifecycle:Binding goals to phases",
			"Exigen:P3:Maven:Checking Code Health:Coding conventions and best practices with Checkstyle, PMD and Findbugs plugins",
			"Exigen:P3:Maven:Checking Code Health:Copy-paste detection with CPD",
			"Exigen:P3:Maven:Checking Code Health:Testing with surefire plugin",
			"Exigen:P3:Maven:Checking Code Health:Test coverage with Cobertura ",
			"Exigen:P3:Maven:Team Collaboration:Creating a shared repository",
			"Exigen:P3:Maven:Team Collaboration:Binary build dependencies on SNAPSHOTs",
			"Exigen:P3:Maven:Team Collaboration:Creating a standard project Archetype",
			"Exigen:P3:SQL:Transactions:Transaction definition and its properties",
			"Exigen:P3:SQL:Transactions:Isolation levels",
			"Exigen:P3:SQL:Transactions:Problems that can occur in different isolation levels",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Software development process:Software development activities",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Basics of SDLC models:Waterfall",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Basics of SDLC models:Spiral",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Basics of SDLC models:Incremental development",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Basics of SDLC models:Agile development",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Basics of SDLC models:Prototyping",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Basics of SDLC models:Rapid Application Development",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Basics of SDLC models:Lean software development",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Scrum:Roles and responsibilities",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Scrum:Artifacts",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Scrum:Flow",
			"Softserve:Engineering Management - Process Planning (SDLC):CL1:Scrum:Ceremonies",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Abiliton SDLC",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Agile:Scrum:Planning",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Agile:Scrum:Reporting",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Agile:Scrum:Scaling projects",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Agile:Agile Unified Process",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Agile:Extreme Programming (XP):Concepts",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Agile:Extreme Programming (XP):Practices",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Agile:Extreme Programming (XP):Planning",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Agile:Extreme Programming (XP):Testing",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Agile:Extreme Programming (XP):Test-driven development",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Agile:Feature Driven Development",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Rational Unified Process (RUP):Key features and best practices",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Rational Unified Process (RUP):Static structure",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Rational Unified Process (RUP):Dynamic structure",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Rational Unified Process (RUP):Use-Case-Driven process",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Software Development Methodologies:Lean software development:Kanban",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Engineering Process Planning:Evaluating technical feasibility",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Engineering Process Planning:Defining unit-testing process",
			"Softserve:Engineering Management - Process Planning (SDLC):CL2:Engineering Process Planning:Defining code review process",
			"Softserve:Engineering Management - Process Planning (SDLC):CL3:Engineering Process Planning:Defining deployment plan",
			"Softserve:Engineering Management - Process Planning (SDLC):CL3:Engineering Process Planning:Defining development environment tools suit",
			"Softserve:Engineering Management - Process Planning (SDLC):CL3:Engineering Process Planning:Microsoft Security Development Lifecycle",
			"Softserve:Engineering Management - Process Planning (SDLC):CL3:Engineering Process Planning:Defining perfomance plan",
			"Softserve:Engineering Management - Process Planning (SDLC):CL3:Engineering Process Planning:Planning for testing (integration/perfomance/stress testing, defining testing environment)",
			"Softserve:Engineering Management - Process Planning (SDLC):CL3:Engineering Process Planning:Calculating velocity of Agile projects",
			"Softserve:Engineering Management - Estimation:CL1:Scope Concept",
			"Softserve:Engineering Management - Estimation:CL1:Estimates, Targets, and Commitments ",
			"Softserve:Engineering Management - Estimation:CL1:Overestimate vs Underestimate ",
			"Softserve:Engineering Management - Estimation:CL1:Decomposition and Recomposition ",
			"Softserve:Engineering Management - Estimation:CL1:Analogy-based estimations ",
			"Softserve:Engineering Management - Estimation:CL1:Story based estimations ",
			"Softserve:Engineering Management - Estimation:CL2:Cone of Uncertainty ",
			"Softserve:Engineering Management - Estimation:CL2:Source of Estimation Errors ",
			"Softserve:Engineering Management - Estimation:CL2:Diseconomies of Scale ",
			"Softserve:Engineering Management - Estimation:CL2:Count, Compute, Judge techniques ",
			"Softserve:Engineering Management - Estimation:CL2:Delphi method",
			"Softserve:Engineering Management - Estimation:CL2:Challenges with Estimating Size ",
			"Softserve:Engineering Management - Estimation:CL2:Challenges with Estimating Effort ",
			"Softserve:Engineering Management - Estimation:CL2:Challenges with Estimating Schedule ",
			"Softserve:Engineering Management - Estimation:CL2:Story based scope definition: scoping project, release planning  ",
			"Softserve:Engineering Management - Estimation:CL2:Documenting and presenting estimation results ",
			"Softserve:Engineering Management - Estimation:CL2:PERT analysis ",
			"Softserve:Engineering Management - Estimation:CL3:Proxy-Based Estimates ",
			"Softserve:Engineering Management - Estimation:CL3:Using Historical Data to Refine Your Estimates ",
			"Softserve:Engineering Management - Estimation:CL3:Political Influences on Estimates ",
			"Softserve:Engineering Management - Estimation:CL3:Functional Point Analysis",
			"Softserve:Engineering Management - Estimation:CL3:Parametric models (COCOMO II, COSYMO or other)",
			"Softserve:Requirements - Software Requirements:CL1:Requirement definition ",
			"Softserve:Requirements - Software Requirements:CL1:Levels of Requirements: Business, User, and Functional requirements Most common requirements risks Characteristics of Excellent Requirements Benefits from a High-Quality Requirements Process ",
			"Softserve:Requirements - Software Requirements:CL1:Root Causes of Project Success and Failure",
			"Softserve:Requirements - Software Requirements:CL1:Sources of Requirements ",
			"Softserve:Requirements - Software Requirements:CL1:Basic Requirements Elicitation Techniques:Brainstorming",
			"Softserve:Requirements - Software Requirements:CL1:Basic Requirements Elicitation Techniques:Interviews",
			"Softserve:Requirements - Software Requirements:CL1:Basic Requirements Elicitation Techniques:Survey/ Questionnaire",
			"Softserve:Requirements - Software Requirements:CL1:Basic Requirements Elicitation Techniques:Document Analysis",
			"Softserve:Requirements - Software Requirements:CL1:Requirements artifacts - SRS (according to IEEE Standard 830-1998)",
			"Softserve:Requirements - Software Requirements:CL2:System requirements",
			"Softserve:Requirements - Software Requirements:CL2:Non-functional requirements",
			"Softserve:Requirements - Software Requirements:CL2:Product champion ",
			"Softserve:Requirements - Software Requirements:CL2:User classes and their characteristics ",
			"Softserve:Requirements - Software Requirements:CL2:Software Quality Attributes ",
			"Softserve:Requirements - Software Requirements:CL2:Assumptions, constraints and their roles ",
			"Softserve:Requirements - Software Requirements:CL2:Requirements Elicitation Techniques:Focus Groups",
			"Softserve:Requirements - Software Requirements:CL2:Requirements Elicitation Techniques:Interface Analysis",
			"Softserve:Requirements - Software Requirements:CL2:Requirements Elicitation Techniques:Observation",
			"Softserve:Requirements - Software Requirements:CL2:Requirements Elicitation Techniques:Requirements Workshops",
			"Softserve:Requirements - Software Requirements:CL2:Requirements Elicitation Techniques:Prototyping",
			"Softserve:Requirements - Software Requirements:CL2:Basic Modeling techniques:Data dictionary and glossary",
			"Softserve:Requirements - Software Requirements:CL2:Basic Modeling techniques:Data flow diagrams",
			"Softserve:Requirements - Software Requirements:CL2:Basic Modeling techniques:ERD",
			"Softserve:Requirements - Software Requirements:CL2:Basic Modeling techniques:Process modeling (flowcharts, activity diagrams)",
			"Softserve:Requirements - Software Requirements:CL2:Requirements artifacts:Product Vision and Scope document etc",
			"Softserve:Requirements - Software Requirements:CL3:Project scope Vs. Product scope (BA Vs. PM responsibilities)",
			"Softserve:Requirements - Software Requirements:CL3:Requirements prioritization",
			"Softserve:Requirements - Software Requirements:CL3:Business rules, their types and context",
			"Softserve:Requirements - Software Requirements:CL3:Requirements development process",
			"Softserve:Requirements - Software Requirements:CL3:Stakeholders, RACI Matrix",
			"Softserve:Requirements - Software Requirements:CL3:Modeling techniques:functional decomposition",
			"Softserve:Requirements - Software Requirements:CL3:Modeling techniques:Scenarios and use cases",
			"Softserve:Requirements - Software Requirements:CL3:Modeling techniques:sequence diagrams",
			"Softserve:Requirements - Software Requirements:CL3:Modeling techniques:State diagrams",
			"Softserve:Requirements - Software Requirements:CL3:Modeling techniques:Event Response Table",
			"Softserve:Requirements - Software Requirements:CL3:Modeling techniques:Decision Tables and Decision Trees",
			"Softserve:Requirements - Software Requirements:CL3:Modeling techniques:Dialog Map",
			"Softserve:Requirements - Software Requirements:CL3:Reviewing requirements - Structured walkthrough, Inspections ",
			"Softserve:Requirements - Software Requirements:CL3:Validating requirements",
			"Softserve:Requirements - Software Requirements:CL3:Change management – Baselines, Change control Board, scope creep, gold plating",
			"Softserve:Requirements - Software Requirements:CL3:Tracing requirements, allocating requirements – traceability matrix etc",
			"Softserve:Design - OOD:CL1: Abstraction",
			"Softserve:Design - OOD:CL1: Encapsulation",
			"Softserve:Design - OOD:CL1: Inheritance vs. Aggregation",
			"Softserve:Design - OOD:CL1: Modularity",
			"Softserve:Design - OOD:CL1: Polymorphism",
			"Softserve:Design - OOD:CL1: Types vs. Classes",
			"Softserve:Design - OOD:CL1: Abstraction Qualities (cohesion, coupling, etc)",
			"Softserve:Design - OOD:CL1: Separation of concerns principle",
			"Softserve:Design - OOD:CL1: Single responsibility principle",
			"Softserve:Design - OOD:CL2:GoF Design Patterns",
			"Softserve:Design - OOD:CL2:Architectural Patterns: Layered Architecture",
			"Softserve:Design - OOD:CL2:Architectural Patterns: MVC",
			"Softserve:Design - OOD:CL2:Architectural Patterns: SOA and EDA",
			"Softserve:Design - OOD:CL2:Architectural Patterns: IoC",
			"Softserve:Design - OOD:CL2:SOLID principles",
			"Softserve:Design - OOD:CL2:Anti-patterns",
			"Softserve:Design - OOD:CL2:Architectural Patterns: MVVM (.NET Desktop Profile)",
			"Softserve:Design - OOD:CL3:Principles of Object Oriented Design",
			"Softserve:Design - OOD:CL3:Patterns of Enterprise Architecture Applications",
			"Softserve:Design - OOD:CL3:Core J2EE Patterns (Java developers only)",
			"Softserve:Design - OOD:CL3:MS Architecture Application Guide (.Net developers only)",
			"Softserve:Design - OOD:CL3:Cloud types and service models",
			"Softserve:Design - OOD:CL3:Cloud computing patterns",
			"Softserve:Design - OOD:CL3:Architecture Qualities",
			"Softserve:Design - DB Design:CL1: Relational terminology: Entities",
			"Softserve:Design - DB Design:CL1: Relational terminology: Attributes",
			"Softserve:Design - DB Design:CL1: Relational terminology: Records (Tuples)",
			"Softserve:Design - DB Design:CL1: Relationships (One-to-One, One-to-Many)",
			"Softserve:Design - DB Design:CL1: Understanding ER notation",
			"Softserve:Design - DB Design:CL1: Understanding normalization concept",
			"Softserve:Design - DB Design:CL1: Data Integrity",
			"Softserve:Design - DB Design:CL2:Understanding RDBMS architecture",
			"Softserve:Design - DB Design:CL2:Transactions: ACID",
			"Softserve:Design - DB Design:CL2:Transactions: Recovery",
			"Softserve:Design - DB Design:CL2:Transactions: Locking",
			"Softserve:Design - DB Design:CL2:Transactions: Isolation",
			"Softserve:Design - DB Design:CL2:Transactions: Concurrency",
			"Softserve:Design - DB Design:CL2:Optimization database (performance, volume) ",
			"Softserve:Design - DB Design:CL2:Optimizing the Database Design by Denormalizing",
			"Softserve:Design - DB Design:CL3:Active Database",
			"Softserve:Design - DB Design:CL3:Data protection and planning security",
			"Softserve:Design - DB Design:CL3:Object-Relational Database Systems",
			"Softserve:Design - DB Design:CL3:Object-Oriented Database Systems",
			"Softserve:Design - DB Design:CL3:Multidimentional databases",
			"Softserve:Design - DB Design:CL3:Distributed databases ",
			"Softserve:Design - Modeling:CL1:UML: Basic Diagram Types",
			"Softserve:Design - Modeling:CL1:UML: Use Case Diagram (Essentials)",
			"Softserve:Design - Modeling:CL1:UML: Class Diagram (Essentials)",
			"Softserve:Design - Modeling:CL1:Entity Relationship Diagrams",
			"Softserve:Design - Modeling:CL1:Data Flow Diagrams",
			"Softserve:Design - Modeling:CL2:UML: Structure Diagrams",
			"Softserve:Design - Modeling:CL2:Class Diagram (Advanced)",
			"Softserve:Design - Modeling:CL2:Component Diagram",
			"Softserve:Design - Modeling:CL2:Composite Structures Diagram",
			"Softserve:Design - Modeling:CL2:Package Diagram",
			"Softserve:Design - Modeling:CL2:Deployment Diagram",
			"Softserve:Design - Modeling:CL2:Object Diagram",
			"Softserve:Design - Modeling:CL2:UML: Behavior Diagrams",
			"Softserve:Design - Modeling:CL2:Activity Diagram",
			"Softserve:Design - Modeling:CL2:Use Case Diagram (Advanced)",
			"Softserve:Design - Modeling:CL2:State Diagram",
			"Softserve:Design - Modeling:CL2:UML: Interaction Diagrams",
			"Softserve:Design - Modeling:CL2:Sequence Diagram",
			"Softserve:Design - Modeling:CL2:Communication Diagram",
			"Softserve:Design - Modeling:CL3:UML: Extensions",
			"Softserve:Design - Modeling:CL3:UML: Object Constraint Language",
			"Softserve:Design - Modeling:CL3:UML: UML 2 Architecture (layers, metamodels)",
			"Softserve:Design - Modeling:CL3:BPMN (Basics)",
			"Softserve:Design-Security:CL1:Information security",
			"Softserve:Design-Security:CL1:Access Control Lists (ACLs)",
			"Softserve:Design-Security:CL1:.NET Framework Cryptography Model",
			"Softserve:Design-Security:CL1:DPAPI",
			"Softserve:Design-Security:CL1:Authentication types",
			"Softserve:Design-Security:CL2:Public-key Infrastructure (PKI)",
			"Softserve:Design-Security:CL2:SSL and TLS",
			"Softserve:Design-Security:CL2:Strong-Named Assemblies",
			"Softserve:Design-Security:CL2:Network security",
			"Softserve:Design-Security:CL2:Code Access Security",
			"Softserve:Design-Security:CL2:Security Application Block",
			"Softserve:Design-Security:CL2:Security tools in .NET Framework",
			"Softserve:Design-Security:CL2:Administering Security Policy using .NET Framework Configuration Tool",
			"Softserve:Design-Security:CL2:Writing firewall-friendly applications",
			"Softserve:Design-Security:CL2:Protecting against buffer overrun attacks",
			"Softserve:Design-Security:CL2:Protecting against canonical representation attacks",
			"Softserve:Design-Security:CL2:Protecting against SQL-injection attacks",
			"Softserve:Design-Security:CL2:Protecting against cross-site scripting attacks",
			"Softserve:Design-Security:CL2:Protecting against DoS attacks",
			"Softserve:Design-Security:CL2:WCF throttling",
			"Softserve:Design-Security:CL3:Threat Modeling Web Applications",
			"Softserve:Design-Security:CL3:Security Development Lifecycle",
			"Softserve:Construction - Language - .Net:CL1:Declare namespaces, classes, interfaces, static and instance class members",
			"Softserve:Construction - Language - .Net:CL1:Types casting",
			"Softserve:Construction - Language - .Net:CL1:Value and reference types",
			"Softserve:Construction - Language - .Net:CL1:Properties and automatic properties",
			"Softserve:Construction - Language - .Net:CL1:Structured Exception Handling",
			"Softserve:Construction - Language - .Net:CL1:System.Collections and System.Collections.Generic namespaces",
			"Softserve:Construction - Language - .Net:CL1:Building enumerable types",
			"Softserve:Construction - Language - .Net:CL1:Building cloneable objects",
			"Softserve:Construction - Language - .Net:CL1:Building comparable types",
			"Softserve:Construction - Language - .Net:CL1:IDisposable interface",
			"Softserve:Construction - Language - .Net:CL1:Generics",
			"Softserve:Construction - Language - .Net:CL1:Nullable types",
			"Softserve:Construction - Language - .Net:CL1:Delegates, events and lambdas",
			"Softserve:Construction - Language - .Net:CL1:Indexers and operators",
			"Softserve:Construction - Language - .Net:CL1:Extension methods",
			"Softserve:Construction - Language - .Net:CL1:Partial methods",
			"Softserve:Construction - Language - .Net:CL1:Anonymous types",
			"Softserve:Construction - Language - .Net:CL1:Strings and StringBuilder class",
			"Softserve:Construction - Language - .Net:CL1:System.Configuration namespace",
			"Softserve:Construction - Language - .Net:CL1:Serialization",
			"Softserve:Construction - Language - .Net:CL1:System.IO namespace",
			"Softserve:Construction - Language - .Net:CL1:Streams",
			"Softserve:Construction - Language - .Net:CL1:LINQ",
			"Softserve:Construction - Language - .Net:CL2:Specialized collections",
			"Softserve:Construction - Language - .Net:CL2:Application domains",
			"Softserve:Construction - Language - .Net:CL2:Custom serialization",
			"Softserve:Construction - Language - .Net:CL2:Garbage collection",
			"Softserve:Construction - Language - .Net:CL2:Custom attributes",
			"Softserve:Construction - Language - .Net:CL2:Reflection",
			"Softserve:Construction - Language - .Net:CL2:COM and .NET Interoperability",
			"Softserve:Construction - Language - .Net:CL2:Regular Expressions",
			"Softserve:Construction - Language - .Net:CL3:CLS",
			"Softserve:Construction - Language - .Net:CL3:Consuming unmanaged DLL functions",
			"Softserve:Construction - Language - .Net:CL3:Interop Marshaling",
			"Softserve:Construction - Language - .Net:CL3:Assembly Loader",
			"Softserve:Construction - Refactoring:CL1:Refactoring Concept (what/when/why)",
			"Softserve:Construction - Refactoring:CL1:Smells Catalog and possible re-factorings",
			"Softserve:Construction - Refactoring:CL1:Moving Features Between Objects (basic):Move Method",
			"Softserve:Construction - Refactoring:CL1:Moving Features Between Objects (basic):Move Field",
			"Softserve:Construction - Refactoring:CL1:Organizing Data (basic):Encapsulate Field",
			"Softserve:Construction - Refactoring:CL1:Organizing Data (basic):Encapsulate Collection",
			"Softserve:Construction - Refactoring:CL1:Composing Methods (basic):Extract Method",
			"Softserve:Construction - Refactoring:CL1:Composing Methods (basic):Inline Method",
			"Softserve:Construction - Refactoring:CL1:Composing Methods (basic):Inline Temp",
			"Softserve:Construction - Refactoring:CL1:Composing Methods (basic):Replace Temp with Query",
			"Softserve:Construction - Refactoring:CL1:Composing Methods (basic):Split Temporary Variable",
			"Softserve:Construction - Refactoring:CL1:Simplifying Conditional Expressions (basic):Decompose Conditional Expression",
			"Softserve:Construction - Refactoring:CL1:Simplifying Conditional Expressions (basic):Consolidate Conditional Expression",
			"Softserve:Construction - Refactoring:CL1:Simplifying Conditional Expressions (basic):Consolidate Duplicate Conditional Fragments",
			"Softserve:Construction - Refactoring:CL1:Simplifying Conditional Expressions (basic):Remove Control Flag",
			"Softserve:Construction - Refactoring:CL1:Simplifying Conditional Expressions (basic):Replace Conditional with Polymorphism",
			"Softserve:Construction - Refactoring:CL2:Making Method Calls Simpler",
			"Softserve:Construction - Refactoring:CL2:Dealing with Generalization",
			"Softserve:Construction - Refactoring:CL2:Creation:Replace Constructors with Creation Methods",
			"Softserve:Construction - Refactoring:CL2:Creation:Move Creation Knowledge to Factory",
			"Softserve:Construction - Refactoring:CL2:Creation:Encapsulate Classes with Factory",
			"Softserve:Construction - Refactoring:CL2:Creation:Encapsulate Composite with Builder",
			"Softserve:Construction - Refactoring:CL2:Simplification:Replace Conditional Logic with Strategy",
			"Softserve:Construction - Refactoring:CL2:Simplification:Replace State-Altering Conditionals with State",
			"Softserve:Construction - Refactoring:CL2:Simplification:Replace Implicit Tree with Composite",
			"Softserve:Construction - Refactoring:CL2:Simplification:Replace Conditional Dispatcher with Command",
			"Softserve:Construction - Refactoring:CL2:Generalization:Form Template Method",
			"Softserve:Construction - Refactoring:CL2:Generalization:Extract Composite",
			"Softserve:Construction - Refactoring:CL2:Generalization:Replace Hard-Coded Notifications with Observer",
			"Softserve:Construction - Refactoring:CL2:Generalization:Red green refactoring",
			"Softserve:Construction - Refactoring:CL3:Protection",
			"Softserve:Construction - Refactoring:CL3:Accumulation",
			"Softserve:Construction - Refactoring:CL3:Utilities",
			"Softserve:Construction - Refactoring:CL3:Re-factor legacy applications",
			"Softserve:Construction - Refactoring:CL3:Re-factor of large scale applications",
			"Softserve:Construction - Concurrency - .Net:CL1:Understand CLR threading",
			"Softserve:Construction - Concurrency - .Net:CL1:lock keyword or System.Threading.Monitor",
			"Softserve:Construction - Concurrency - .Net:CL1:Asynchronous operations",
			"Softserve:Construction - Concurrency - .Net:CL1:volatile fields",
			"Softserve:Construction - Concurrency - .Net:CL1:System.Threading.Thread class",
			"Softserve:Construction - Concurrency - .Net:CL1:Deadlock problem",
			"Softserve:Construction - Concurrency - .Net:CL2:System.Threading.ThreadPool",
			"Softserve:Construction - Concurrency - .Net:CL2:Inerlocked functions",
			"Softserve:Construction - Concurrency - .Net:CL2:Using kernel synchronization objects in .NET",
			"Softserve:Construction - Concurrency - .Net:CL2:Win32: Window messaging, message queues",
			"Softserve:Construction - Concurrency - .Net:CL2:Wait Handles",
			"Softserve:Construction - Concurrency - .Net:CL2:ReaderWriterLockSlim Class",
			"Softserve:Construction - Concurrency - .Net:CL2:System.Collections.Concurrent Namespace",
			"Softserve:Construction - Concurrency - .Net:CL2:System.Threading.Tasks Namespace",
			"Softserve:Construction - Concurrency - .Net:CL2:Multithreading in components",
			"Softserve:Construction - Concurrency - .Net:CL2:Parallel programming",
			"Softserve:Construction - Concurrency - .Net:CL2:Asynchronous Programming with Async and Await",
			"Softserve:Construction - Concurrency - .Net:CL2:WPF Threading Model (.NET Desktop Profile)",
			"Softserve:Construction - Concurrency - .Net:CL3:File mapping",
			"Softserve:Construction - Concurrency - .Net:CL3:Grid computing, clustering",
			"Softserve:Construction - Concurrency - .Net:CL3:TPL Dataflow",
			"Softserve:Product deploying, software installation-.Net:CL1:Publishing Web sites (.NET Web Profile)",
			"Softserve:Product deploying, software installation-.Net:CL1:Publishing Web Services (.NET Desktop Profile)",
			"Softserve:Product deploying, software installation-.Net:CL1:Creating Setup Project",
			"Softserve:Product deploying, software installation-.Net:CL1:Creating Web Setup Project (.NET Web Profile)",
			"Softserve:Product deploying, software installation-.Net:CL1:Adding output to installation project",
			"Softserve:Product deploying, software installation-.Net:CL1:Installation Prerequisites",
			"Softserve:Product deploying, software installation-.Net:CL1:Registering assemblies in GAC",
			"Softserve:Product deploying, software installation-.Net:CL2:File types and registry editor",
			"Softserve:Product deploying, software installation-.Net:CL2:Custom actions and UI editor",
			"Softserve:Product deploying, software installation-.Net:CL2:Installation Events",
			"Softserve:Product deploying, software installation-.Net:CL2:ClickOnce Deployment",
			"Softserve:Product deploying, software installation-.Net:CL2:Deploying a WPF Application (.NET Desktop Profile)",
			"Softserve:Product deploying, software installation-.Net:CL3:Remoting Application Deployment",
			"Softserve:Product deploying, software installation-.Net:CL3:Creating Installation package for Windows Service",
			"Softserve:Product deploying, software installation-.Net:CL3:Deploying an Application for COM Access",
			"Softserve:Product deploying, software installation-.Net:CL3:Windows Installer Deployment",
			"Softserve:Product deploying, software installation-.Net:CL3:WiX Toolset",
			"Softserve:Construction - Networking:CL1:Understanding networks: layers and protocols",
			"Softserve:Construction - Networking:CL1:Basic understanding of TCP/IP model and protocols",
			"Softserve:Construction - Networking:CL1:Basic knowledge of physical layer protocols and media",
			"Softserve:Construction - Networking:CL1:Application layer protocols basics (HTTP, FTP, Telnet)",
			"Softserve:Construction - Networking:CL1:Understanding HTTP and WWW",
			"Softserve:Construction - Networking:CL1:Basic troubleshooting tools (ICMP, ping, traceroute)",
			"Softserve:Construction - Networking:CL1:Client/Server model",
			"Softserve:Construction - Networking:CL1:Sockets, IP and port addressing",
			"Softserve:Construction - Networking:CL1:Using proxy server",
			"Softserve:Construction - Networking:CL1:File transfer services: FTP, TFTP",
			"Softserve:Construction - Networking:CL1:Name resolution services: DNS, whois",
			"Softserve:Construction - Networking:CL1:Remote access services: Telnet, SSH, rdesktop, VNC",
			"Softserve:Construction - Networking:CL2:Detailed OSI and TCP/IP models",
			"Softserve:Construction - Networking:CL2:IP addressing protocols (DHCP, BOOTP, ARP)",
			"Softserve:Construction - Networking:CL2:Mail protocols: POP3/IMAP/SMTP",
			"Softserve:Construction - Networking:CL2:File sharing services: NFS, SMB, NetBIOS",
			"Softserve:Construction - Networking:CL2:IPv4 transport and network layer protocols",
			"Softserve:Construction - Networking:CL2:IP addressing: subnetting, CIDR and VLSM",
			"Softserve:Construction - Networking:CL2:Unicast, Broadcast, Multicast",
			"Softserve:Construction - Networking:CL2:NAT, Port Forwarding and DMZ",
			"Softserve:Construction - Networking:CL2:Using network tools (tcpdump, nmap, WireShark)",
			"Softserve:Construction - Networking:CL2:Secure connections with SSL/TLS",
			"Softserve:Construction - Networking:CL2:VPN and tunnels",
			"Softserve:Construction - Networking:CL2:Basic understanding of IP routing",
			"Softserve:Construction - Networking:CL3:Transport Layer: purpose, protocols, port addressing",
			"Softserve:Construction - Networking:CL3:In-depth knowledge of protocols and technologies of all TCP/IP layers",
			"Softserve:Construction - Networking:CL3:Detailed LAN technologies: VLANs, spanning tree, etherchannel",
			"Softserve:Construction - Networking:CL3:WAN: leased lines and channel types, topologies, access technologies",
			"Softserve:Construction - Networking:CL3:Network design principles (modules, approaches, best practices)",
			"Softserve:Construction - Networking:CL3:Network lifecycle model (Plan, Design, Implement, Operate, Optimize, Dispose)",
			"Softserve:Construction - Networking:CL3:Network troubleshooting methodologies",
			"Softserve:Construction - Networking:CL3:IPv6",
			"Softserve:Construction - Networking:CL3:Major network hardware vendors and tendencies",
			"Softserve:Construction - Networking:CL3:Network hardware: hubs, switches, routers, bridges",
			"Softserve:Construction - Networking:CL3:Network security and threats",
			"Softserve:Construction - Networking:CL3:Dynamic routing and routing protocols (RIP, OSPF, EIGRP, BGP, IS-IS)",
			"Softserve:Construction - Networking:CL3:Network and systems management",
			"Softserve:Construction - Networking:CL3:Wireless networks",
			"Softserve:Internationalization - .Net:CL1:Localization:Global Resource",
			"Softserve:Internationalization - .Net:CL1:Localization:Local Resource Expression (Explicit, Implicit)",
			"Softserve:Internationalization - .Net:CL1:Internationalization",
			"Softserve:Internationalization - .Net:CL1:Globalization:User interface issues",
			"Softserve:Internationalization - .Net:CL1:Globalization:Natural language issues",
			"Softserve:Internationalization - .Net:CL1:Globalization:Data formatting issues",
			"Softserve:Internationalization - .Net:CL1:Globalization:String-related issues",
			"Softserve:Internationalization - .Net:CL1:Globalization:System. Globalization Namespace",
			"Softserve:Internationalization - .Net:CL2:Creating a satellite assembly",
			"Softserve:Internationalization - .Net:CL2:Creating a file based resource manager",
			"Softserve:Internationalization - .Net:CL2:Using Calendars for Specific Cultures",
			"Softserve:Internationalization - .Net:CL2:Formatting Numeric Data for a Specific Culture",
			"Softserve:Internationalization - .Net:CL2:Comparing and Sorting Data for a Specific Culture",
			"Softserve:Internationalization - .Net:CL2:System.Text Namespace",
			"Softserve:Internationalization - .Net:CL3:Using a Database for Localization",
			"Softserve:Internationalization - .Net:CL3:Localization in WPF Applications (Locbaml)",
			"Softserve:Construction - UI Elements (WPF):CL1:WPF Application life cycle and Application class",
			"Softserve:Construction - UI Elements (WPF):CL1:XAML namespaces",
			"Softserve:Construction - UI Elements (WPF):CL1:Declaring properties and events in XAML",
			"Softserve:Construction - UI Elements (WPF):CL1:Layout containers",
			"Softserve:Construction - UI Elements (WPF):CL1:Using VisualTreeHelper class",
			"Softserve:Construction - UI Elements (WPF):CL1:Event bubbling",
			"Softserve:Construction - UI Elements (WPF):CL1:Executing commands and WPF Command Model",
			"Softserve:Construction - UI Elements (WPF):CL1:Dependency properties",
			"Softserve:Construction - UI Elements (WPF):CL1:Attached properties",
			"Softserve:Construction - UI Elements (WPF):CL1:Routed events",
			"Softserve:Construction - UI Elements (WPF):CL1:Data binding",
			"Softserve:Construction - UI Elements (WPF):CL1:Basic UI controls",
			"Softserve:Construction - UI Elements (WPF):CL1:User controls",
			"Softserve:Construction - UI Elements (WPF):CL1:Content controls",
			"Softserve:Construction - UI Elements (WPF):CL1:Windows (positioning windows, interaction between windows, modal windows)",
			"Softserve:Construction - UI Elements (WPF):CL1:Basic shapes",
			"Softserve:Construction - UI Elements (WPF):CL1:Brushes",
			"Softserve:Construction - UI Elements (WPF):CL1:Defining and retrieving resources",
			"Softserve:Construction - UI Elements (WPF):CL1:Static and dynamic resources",
			"Softserve:Construction - UI Elements (WPF):CL2:Markup Extensions",
			"Softserve:Construction - UI Elements (WPF):CL2:Paths and geometries",
			"Softserve:Construction - UI Elements (WPF):CL2:B?zier Curves",
			"Softserve:Construction - UI Elements (WPF):CL2:Building localizable UI",
			"Softserve:Construction - UI Elements (WPF):CL2:Data validation",
			"Softserve:Construction - UI Elements (WPF):CL2:Data conversion",
			"Softserve:Construction - UI Elements (WPF):CL2:Types conversion",
			"Softserve:Construction - UI Elements (WPF):CL2:Resource dictionaries",
			"Softserve:Construction - UI Elements (WPF):CL2:Drawing visuals",
			"Softserve:Construction - UI Elements (WPF):CL2:Creating control templates",
			"Softserve:Construction - UI Elements (WPF):CL2:Data templates",
			"Softserve:Construction - UI Elements (WPF):CL2:Data views",
			"Softserve:Construction - UI Elements (WPF):CL2:VirtualizingPanel and VirtualizingStackPanel classes",
			"Softserve:Construction - UI Elements (WPF):CL2:ObjectDataProvider and XmlDataProvider classes",
			"Softserve:Construction - UI Elements (WPF):CL2:Ribbon control",
			"Softserve:Construction - UI Elements (WPF):CL3:Creating XAML Browser Applications (XBAPs)",
			"Softserve:Construction - UI Elements (WPF):CL3:WPF and Win32 Interoperation",
			"Softserve:Construction - UI Elements (WPF):CL3:Touch Support in WPF",
			"Softserve:Construction - UI Elements (WPF):CL3:Cached Composition (BitmapCache and BitmapCacheBrush classes)",
			"Softserve:Construction - UI Elements (WPF):CL3:HTML-XBAP Script Interop",
			"Softserve:Construction - UI Elements (WPF):CL3:Interaction with Windows OS taskbar",
			"Softserve:Construction - UI Elements (WPF):CL3:Printing",
			"Softserve:Construction - Styles and Behaviors (WPF):CL1:Defining a style ",
			"Softserve:Construction - Styles and Behaviors (WPF):CL1:Applying a style ",
			"Softserve:Construction - Styles and Behaviors (WPF):CL1:Applying styles by type ",
			"Softserve:Construction - Styles and Behaviors (WPF):CL2:Style inheritance  ",
			"Softserve:Construction - Styles and Behaviors (WPF):CL2:Triggers ",
			"Softserve:Construction - Styles and Behaviors (WPF):CL2:Behaviors ",
			"Softserve:Construction - Styles and Behaviors (WPF):CL3:WPF Themes ",
			"Softserve:Construction - Styles and Behaviors (WPF):CL3:Changing themes dynamically ",
			"Softserve:Construction - Transforms and animation (WPF):CL1:Storyboard class  ",
			"Softserve:Construction - Transforms and animation (WPF):CL1:Basic transforms ",
			"Softserve:Construction - Transforms and animation (WPF):CL2:Timer-based and property-based animation ",
			"Softserve:Construction - Transforms and animation (WPF):CL2:Animation classes ",
			"Softserve:Construction - Transforms and animation (WPF):CL2:Simultaneous animations ",
			"Softserve:Construction - Transforms and animation (WPF):CL2:Overlapping animations ",
			"Softserve:Construction - Transforms and animation (WPF):CL2:Animation lifetime ",
			"Softserve:Construction - Transforms and animation (WPF):CL2:Timeline Class ",
			"Softserve:Construction - Transforms and animation (WPF):CL2:Animating transforms ",
			"Softserve:Construction - Transforms and animation (WPF):CL2:Key Frame Animation ",
			"Softserve:Construction - Transforms and animation (WPF):CL3:Easing functions  ",
			"Softserve:Construction - Transforms and animation (WPF):CL3:Path-Based Animation  ",
			"Softserve:Construction - Transforms and animation (WPF):CL3:Frame-Based Animation  ",
			"Softserve:Construction - Transforms and animation (WPF):CL3:Setting frame rate  ",
			"Softserve:Construction - Transforms and animation (WPF):CL3:3D Drawing  ",
			"Softserve:Construction - Media support (WPF):CL1:SoundPlayer class ",
			"Softserve:Construction - Media support (WPF):CL1:SoundPlayerAction class ",
			"Softserve:Construction - Media support (WPF):CL1:MediaElement class ",
			"Softserve:Construction - Media support (WPF):CL1:VisualBrush class ",
			"Softserve:Construction - Media support (WPF):CL1:MediaPlayer class ",
			"Softserve:Construction - Media support (WPF):CL2:SystemSounds class  ",
			"Softserve:Construction - Media support (WPF):CL2:Synchronizing animation with audio  ",
			"Softserve:Construction - Media support (WPF):CL2:Video effects  ",
			"Softserve:Construction - Media support (WPF):CL2:VideoDrawing class  ",
			"Softserve:Construction - Media support (WPF):CL3:Playing multiple sounds ",
			"Softserve:Construction - Media support (WPF):CL3:Speech synthesis and speech recognition ",
			"Softserve:Construction - Navigation (WPF):CL1:Hyperlink class ",
			"Softserve:Construction - Navigation (WPF):CL1:Frame and Page classes ",
			"Softserve:Construction - Navigation (WPF):CL1:Navigation History ",
			"Softserve:Construction - Navigation (WPF):CL1:Navigation Events ",
			"Softserve:Construction - Navigation (WPF):CL1:Managing the Journal ",
			"Softserve:Construction - Navigation (WPF):CL1:Navigation Service ",
			"Softserve:Construction - Navigation (WPF):CL1:Navigation Hosts ",
			"Softserve:Construction - Navigation (WPF):CL2:Fragment Navigation  ",
			"Softserve:Construction - Navigation (WPF):CL2:Navigation Lifetime  ",
			"Softserve:Construction - Navigation (WPF):CL2:Page Lifetime  ",
			"Softserve:Construction - Navigation (WPF):CL2:Navigating to Content Other than XAML Pages  ",
			"Softserve:Construction - Navigation (WPF):CL2:Structured Navigation  ",
			"Softserve:Construction - Navigation (WPF):CL2:Retaining Content State with Navigation History  ",
			"Softserve:Construction - Navigation (WPF):CL2:Storing data using cookies  ",
			"Softserve:Construction - Navigation (WPF):CL3:Navigation Topologies ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Modular applications concepts ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Defining a module ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Modules loading ('When available' and 'On demand' options) ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Module catalogs ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Specifying Module Dependencies ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Shell ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Bootstrapper ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Dependency injection ",
			"Softserve:Construction - Prism Framework (WPF):CL1:UnityContainer (configuration, registering and resolving types and instances) ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Regions and RegionManager ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Navigation in Prism (State-Based and View-Based navigation) ",
			"Softserve:Construction - Prism Framework (WPF):CL1:Event aggregation ",
			"Softserve:Construction - Prism Framework (WPF):CL1:ServiceLocator ",
			"Softserve:Construction - Prism Framework (WPF):CL2:MEF (configuration, registering and resolving types and instances)  ",
			"Softserve:Construction - Prism Framework (WPF):CL2:Using the NavigationJournal  ",
			"Softserve:Construction - Prism Framework (WPF):CL2:Lifetime managers  ",
			"Softserve:Construction - Prism Framework (WPF):CL3:Region adapters ",
			"Softserve:Construction - Prism Framework (WPF):CL3:Region behaviors ",
			"Softserve:Construction - Prism Framework (WPF):CL3:Changing Logical Navigation Structure ",
			"Softserve:Construction - Prism Framework (WPF):CL3:Advanced commanding scenarios (composite commands, child commands, commands within collections) ",
			"Softserve:Construction - Prism Framework (WPF):CL3:Extending Prism Command Behaviors ",
			"Softserve:Security:CL1:Authentication in unix",
			"Softserve:Security:CL1:Understanding security reasons of user groups, /etc/shadow and  /etc/group files.",
			"Softserve:Security:CL1:Standard unix filesystem permissions",
			"Softserve:Security:CL1:PAM (Pluggable Authentication Modules)",
			"Softserve:Security:CL1:Chroot, jails and containers",
			"Softserve:Security:CL1:Using sudo",
			"Softserve:Security:CL1:History",
			"Softserve:Security:CL2:Firewalls and packet filters. Iptables, Ipfw",
			"Softserve:Security:CL2:Two factor authentication",
			"Softserve:Security:CL2:Dealing with security incidents",
			"Softserve:Security:CL2:Public Key Cryptography (principles and tools)",
			"Softserve:Security:CL3:Centralised accounts: LDAP and Kerberos",
			"Softserve:Security:CL3:Risk and risk management",
			"Softserve:Security:CL3:Defense practices",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Windows 8 touch language",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines for mouse interactions",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines for keyboard interactions",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Navigation patterns",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Commanding patterns",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Touch interaction patterns",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines for common user interactions",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines for layouts",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines for scaling to screens",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines for panning",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines for resizing",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines for tiles and badges",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines and checklist for toast notifications",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines for app settings",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines and checklist for splash screens",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL1:Guidelines for app suspend and resume",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Advertising quidelines",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Guidelines for visual feedback",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Guidelines for cross-slide",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Guidelines for optical zoom and resizing",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Guidelines for selecting text and images",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Guidelines for snapped and fill views",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Guidelines and checklist for search",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Guidelines for sharing content",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Guidelines and checklist for secondary tiles",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Guidelines and checklist for push notifications",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL2:Guidelines and checklist for globalizing app",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL3:Guidelines for touch targeting",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL3:Guidelines for Semantic Zoom",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL3:Guidelines for rotation",
			"Softserve:Construction - UX guidelines (Windows Store Applications):CL3:Guidelines for pen/stylus interactions",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Common controls",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Dependency properties and Windows Runtime properties",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Data binding",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Routed events",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Commanding",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Adding controls and handling events",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:XAML basics",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Creating UI with XAML",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Control templates",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Applying implicit and explicit styles to controls",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Using based-on styles",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Layout controls",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Handling pointer input",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Frame and Page classes",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Navigation support in page templates",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Creating and updating tiles",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Immediate and app resources, Resource dictionaries",
			"Softserve:Construction - UI construction (Windows Store Applications):CL1:Using brushes (SolidColorBrush, LinearGradientBrush, ImageBrush and WebViewBrush classes)",
			"Softserve:Construction - UI construction (Windows Store Applications):CL2:Application capability declarations",
			"Softserve:Construction - UI construction (Windows Store Applications):CL2:Pinning secondary tiles",
			"Softserve:Construction - UI construction (Windows Store Applications):CL2:Windows.Globalization namespace",
			"Softserve:Construction - UI construction (Windows Store Applications):CL2:Adding a splash screen",
			"Softserve:Construction - UI construction (Windows Store Applications):CL2:Drawing shapes",
			"Softserve:Construction - UI construction (Windows Store Applications):CL2:Creating and updating badges",
			"Softserve:Construction - UI construction (Windows Store Applications):CL2:Creating settings page",
			"Softserve:Construction - UI construction (Windows Store Applications):CL3:Special use capabilities",
			"Softserve:Construction - UI construction (Windows Store Applications):CL3:Printing",
			"Softserve:Construction - UI construction (Windows Store Applications):CL3:Responding to motion and orientation sensors",
			"Softserve:Construction - UI construction (Windows Store Applications):CL3:Responding to changes in lighting",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL1:Controls with built in animation (FlipView, ProgressRing, ToolTip)",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL1:Storyboard class",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL1:Transition animations",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL1:Theme transitions",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL1:Theme animations",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL1:Creating custom animations",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL1:Animating XAML attached properties",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL1:MediaElement class",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL2:Key-frame animations",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL2:Easing functions",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL2:Streaming media to devices using Play To",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL2:Working with audio streams",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL3:Creating 3D effects",
			"Softserve:Construction - Media and animation (Windows Store Applications):CL3:Auto-launching applications with AutoPlay",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL1:Application lifecycle",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL1:Application activation",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL1:Suspending applications",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL1:Handling application visibility change",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL1:Resuming applications",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL1:Closing applications",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL1:Handling exceptions",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL2:Auto-launching applications with file and URI associations",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL2:Handling application activation from toast notifications",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL3:Declaring lock screen capabilities",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL3:Prompting the user to place application tile on the lock screen",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL3:Sending information to the lock screen",
			"Softserve:Construction - App state and lock screen management (Windows Store Applications):CL3:Showing tile and badge updates on the lock screen",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",
			"--------",// 256
																};

}
